Allow defining custom declared license mappings via package curations
oss-review-toolkit/ort pull request #3032
Opened 2020-09-04 09:20 UTC by fviernau

I decided for making the entries additive, so that multiple declared license mapping curations can be applied to
any packages, and the entries are added. They override only if the keys equal. This approach is a good basis for enabling the curation of declared license mappings on broader scopes, e.g. by introducing wildcards to the identifier matching of curations.

See the individual commits for the details.

Fixes #2898.

2020-09-04 14:34 UTC, mnonnenmacher requested changes

2020-09-04 16:03 UTC, fviernau commented on examples/curations.yml
> +      "BSD-derived (http://www.repoze.org/LICENSE.txt)": "LicenseRef-scancode-repoze"
no I don't, at least not quickly. Do you have any?

2020-09-07 10:27 UTC, fviernau commented on examples/curations.yml
> +      "BSD-derived (http://www.repoze.org/LICENSE.txt)": "LicenseRef-scancode-repoze"
@mnonnenmacher can we keep it as is for now?

2020-09-07 12:21 UTC, mnonnenmacher commented on examples/curations.yml
> +      "BSD-derived (http://www.repoze.org/LICENSE.txt)": "LicenseRef-scancode-repoze"
Yes

2020-09-07 12:21 UTC, mnonnenmacher approved these changes

2020-09-07 12:25 UTC, merged