Consistently use configurable license file patterns
oss-review-toolkit/ort pull request #3464
Opened 2020-12-17 14:13 UTC by fviernau

This PR ensures that the configured license filename patterns are consistently used all over the place, except for the tests.

2020-12-18 14:33 UTC, mnonnenmacher requested changes

2020-12-18 14:33 UTC, mnonnenmacher commented on reporter/src/main/kotlin/model/EvaluatedModelMapper.kt
> +    }
Maybe to reduce nesting:
```
private val findingsMatcher = FindingsMatcher(RootLicenseMatcher(input.ortConfig.licenseFilePatterns ?: LicenseFilenamePatterns.DEFAULT)`

2020-12-18 14:33 UTC, mnonnenmacher commented on model/src/main/kotlin/ScanResult.kt
> +import org.ossreviewtoolkit.model.config.LicenseFilenamePatterns
Empty line above instead of below.

2020-12-18 14:34 UTC, mnonnenmacher requested changes

2020-12-18 14:34 UTC, mnonnenmacher commented on cli/src/main/kotlin/commands/EvaluatorCommand.kt
> +import org.ossreviewtoolkit.model.config.LicenseFilenamePatterns
Commit message: Typo in "Resovler"

2020-12-18 14:42 UTC, fviernau commented on cli/src/main/kotlin/commands/EvaluatorCommand.kt
> +import org.ossreviewtoolkit.model.config.LicenseFilenamePatterns
Done.

2020-12-18 14:42 UTC, fviernau commented on reporter/src/main/kotlin/model/EvaluatedModelMapper.kt
> +    }
Done.

2020-12-18 14:42 UTC, fviernau commented on model/src/main/kotlin/ScanResult.kt
> +import org.ossreviewtoolkit.model.config.LicenseFilenamePatterns
Done.

2020-12-18 14:51 UTC, mnonnenmacher approved these changes

2020-12-18 16:23 UTC, merged

2020-12-21 10:49 UTC, sschuberth commented
FYI @durikr, you might be interested in this if you also want to archive `NOTICE` files, which is something you can configure now.