Bower: Add support for authors
oss-review-toolkit/ort pull request #3690
Opened 2021-02-26 13:02 UTC by bs-ondem

Extract information about the authors of a package from the bower.json
definition file and make it available in the metadata of packages and
project.

Signed-off-by: Onur Demirci <onur.demirci@bosch.io>

2021-02-26 14:40 UTC, sschuberth commented
There's a *detekt* violation, please check.

2021-02-26 14:42 UTC, sschuberth requested changes

2021-02-26 14:42 UTC, sschuberth commented on analyzer/src/main/kotlin/managers/Bower.kt
> +            }
Please wait until https://github.com/oss-review-toolkit/ort/pull/3684 is merged, then rebase, and make use to the new central `parseAuthorString()` function here.

2021-02-26 14:43 UTC, sschuberth commented on analyzer/src/main/kotlin/managers/Bower.kt
> +        private fun extractAuthors(node: JsonNode): SortedSet<String> =
To align with other similar functions, this should probably be named `parseAuthrors`.

2021-02-26 15:44 UTC, bs-ondem commented
@sschuberth _detekt_ is complaining about `TooManyFunctions` in the companion object. Can i just add `@Suppress("TooManyFunctions")` like in other classes e.g. Conan.kt?

2021-02-26 15:50 UTC, sschuberth commented
> Can i just add `@Suppress("TooManyFunctions")` like in other classes e.g. Conan.kt?

Basically yes, but my guess is you won't need this anymore when rebasing and using the central function instead of your own.

2021-03-01 14:25 UTC, bs-ondem commented
@sschuberth I'm still getting the `TooManyFunctions` _detekt_ error although I'm using the `PackageManager::parseAuthorString` function.

2021-03-01 14:28 UTC, sschuberth commented
> @sschuberth I'm still getting the `TooManyFunctions` _detekt_ error although I'm using the `PackageManager::parseAuthorString` function.

It was just a *guess* anyway. So you're out of luck and that single added function made a difference 😉

2021-03-02 06:56 UTC, sschuberth approved these changes

2021-03-02 06:56 UTC, merged