analyzer: Fix SPDX metadata to point to a source artifact
oss-review-toolkit/ort pull request #3787
Opened 2021-03-19 10:52 UTC by sschuberth

The "curl-7.70.0.tar.gz" archive contains the source code, so it should
be treated as a source artifact instead of a binary artifact, which is
signalled by setting "filesAnalyzed" to "true".

Also see 15512d3.

Signed-off-by: Sebastian Schuberth <sebastian.schuberth@bosch.io>

2021-03-19 13:10 UTC, tsteenbe requested changes
We  can't set filesAnalyzed to `true` as then [Package Verification Code](https://spdx.github.io/spdx-spec/3-package-information/#39-package-verification-code) becomes mandatory per the spec which is something we don't want as makes creating [SPDX package manifest|https://github.com/spdx/spdx-spec/issues/439] more complicated. 

The current definition of "Files Analyzed"  has been problematic since I started working on SPDX, hope to drop it from the spec in 3.0.

2021-03-19 14:10 UTC, sschuberth commented
> We can't set filesAnalyzed to `true` as then [Package Verification Code](https://spdx.github.io/spdx-spec/3-package-information/#39-package-verification-code) becomes mandatory per the spec

Argh. Fortunately, our SPDX reader does not check for that 😁 So maybe we could slightly violate the spec here? Or, maybe we could simply set `packageVerificationCode` to `NONE`?

> hope to drop it from the spec in 3.0.

How would v3 then distinguish between download URLs of binary vs sources? Ideally, these would just be separate fields (like in ORT 😉 ) so that you can also capture both at the same time.

2021-03-27 11:19 UTC, sschuberth commented
Ping @tsteenbe, mind having another look?

2021-04-06 18:59 UTC, tsteenbe commented
@sschuberth Setting filesAnalyzed to true and not providing Package Verification Code will cause an exception in SPDX reader whilst keeping it false and misusing  downloadLocation as source code location will not cause any issues.

2021-04-06 19:34 UTC, sschuberth commented
> Setting filesAnalyzed to true and not providing Package Verification Code will cause an exception in SPDX reader

*Which* reader exactly?

> misusing downloadLocation as source code location will not cause any issues.

But we'll also have no man to tell that it *is* a source location. It will be treated as a *binary* location instead.

2021-04-06 20:37 UTC, sschuberth commented
Anyway, I've added the `packageVerificationCode` fields now.

2021-04-07 09:24 UTC, neubs-bsi reviewed
would it not make sense to have the changes in the same commit, as otherwise there will be a commit which "cause[s] an exception in [the] SPDX reader"

2021-04-07 10:42 UTC, sschuberth commented
> would it not make sense to have the changes in the same commit, as otherwise there will be a commit which "cause[s] an exception in [the] SPDX reader"

I didn't want to "mix-in" an otherwise unrelated change to `project.spdx.yml`, that's why I separated the commits. I'll simply swap the order of the commits to make it impossible to run such an SPDX reader on an invalid file in our Git history.

2021-04-07 12:56 UTC, tsteenbe requested changes
@sschuberth  Adding just packageVerificationCode with filesAnalyzed set to true you also for instance need to add  PackageLicenseInfoFromFiles see https://spdx.github.io/spdx-spec/3-package-information/#314-all-licenses-information-from-files

It's a bad idea to set filesAnalyzed to true

2021-04-07 13:02 UTC, sschuberth commented
> It's a bad idea to set filesAnalyzed to true

But how can we then distinguish between `downloadLocation`s to source artifacts vs, `downloadLocation`s to binary artifacts?

2021-04-08 21:21 UTC, tsteenbe commented
> But how can we then distinguish between downloadLocations to source artifacts vs, downloadLocations to binary artifacts?

A rather simple solution for that would be to require that source artifacts have to use VCS identifiers in the URLs e.g. git+https://git.myproject.org/MyProject.git. I know this does not work for maven source artifacts but for the few exceptions we could build in regexes to detected the edge cases.

2021-04-09 07:05 UTC, sschuberth commented
> I know this does not work for maven source artifacts but for the few exceptions we could build in regexes to detected the edge cases.

Unfortunately, it's not only a "few exceptions". We heavily rely on custom SPDX files that refer to source artifacts in ZIP files in arbitrary locations. There's no sane way to deal with these with regexes.

2021-04-09 09:33 UTC, neubs-bsi approved these changes

2021-11-23 13:54 UTC, sschuberth commented
@tsteenbe I just checked on this PR again. I'm reading the spec so that for `filesAnalyzed == true`

- the `packageVerificationCode` has a [cardinality of 0..1](https://spdx.github.io/spdx-spec/package-information/#79-package-verification-code-field)
- the `packageLicenseInfoFromFiles` has a [cardinality of 0..*](https://spdx.github.io/spdx-spec/package-information/#714-all-licenses-information-from-files-field)

So as both allow a cardinality of 0, these fields should be optional even with `filesAnalyzed == true`. Do we agree here?

2021-12-07 07:52 UTC, sschuberth commented
Closing this in favor of the different approach in https://github.com/oss-review-toolkit/ort/pull/4816.

2021-12-07 07:52 UTC, closed without merging