helper-cli: Improve curation import and export
oss-review-toolkit/ort pull request #3891
Opened 2021-04-14 10:51 UTC by fviernau

Use only the "matcher" attributes for determining whether an existing entry shall be replaced.

2021-04-14 12:04 UTC, mnonnenmacher requested changes

2021-04-14 12:04 UTC, mnonnenmacher commented on helper-cli/src/main/kotlin/common/Utils.kt
> + * This class holds the matcher attributes of a corresponding [LicenseFindingCuration]. It is supposed to be used for
Remove "for" at the end.

2021-04-14 18:14 UTC, sschuberth approved these changes

2021-04-15 08:00 UTC, merged

2021-04-15 08:00 UTC, fviernau commented
Merged despite the unrelated test failure