postgresql: Use default schema if not defined
oss-review-toolkit/ort pull request #3982
Opened 2021-05-05 09:57 UTC by heliocastro

schema now is not required and always fallback on postgresql default
public schema.
Custom schemas need to be created and granted previously on database

Signed-off-by: Helio Chissini de Castro <helio@kde.org>

Please ensure that your pull request adheres to our [contribution guidelines](https://github.com/oss-review-toolkit/ort/blob/master/CONTRIBUTING.md). Thank you!

2021-05-05 10:14 UTC, sschuberth submitted a review, later dismissed

2021-05-05 10:14 UTC, sschuberth commented on README.md
> +The database needs to exist. If the schema is defined and is not the default postgress _public_, it need to be previously created and grant usage for the specific database user. Left schema entry emp
Second sentence:

    If the schema is set to something else than the default of "public", it needs to exist and be accessible by the configured username.

2021-05-05 10:14 UTC, sschuberth commented on model/src/main/resources/reference.conf
> +        username = username
Please remove the trailing space.

2021-05-05 10:14 UTC, sschuberth commented on README.md
> +        schema = "public"
Commit message:

```
postgres: Use default schema if none defined

The schema now is an optional parameter as the postgres default of "public"
is used.
```

There is no need to repeat too much of the README docs here.

2021-05-05 13:17 UTC, mnonnenmacher requested changes

2021-05-05 13:17 UTC, mnonnenmacher commented on model/src/main/kotlin/utils/DatabaseUtils.kt
> -        }
The schema could be set to a blank string in the configuration file so this check is still valid.

2021-05-12 13:07 UTC, mnonnenmacher approved these changes

2021-05-12 13:08 UTC, merged