Dependency updates
oss-review-toolkit/ort pull request #4302
Opened 2021-07-26 11:09 UTC by fviernau

See the individual commits.

2021-07-26 11:30 UTC, sschuberth requested changes

2021-07-26 11:30 UTC, sschuberth commented on gradle.properties
> +taskinfoPluginVersion = 1.3.0
Commit message: s/1.0.5/1.3.0/

2021-07-26 11:38 UTC, sschuberth approved these changes

2021-07-26 15:34 UTC, fviernau commented
@sschuberth upgrading jackson made the DotNetFunTest(s) fail, so I dropped it for now.

2021-07-26 15:44 UTC, sschuberth approved these changes

2021-07-27 07:27 UTC, merged

2021-07-29 15:55 UTC, sschuberth commented
> @sschuberth upgrading jackson made the DotNetFunTest(s) fail, so I dropped it for now.

I've commented about that [here](https://github.com/FasterXML/jackson-dataformat-xml/issues/469#issuecomment-889263504). Let's see if there's some feedback.