Webapp Updates and Bug Fixes
oss-review-toolkit/ort pull request #4450
Opened 2021-09-10 09:50 UTC by tsteenbe

See individual commits for details.

2021-09-13 11:31 UTC, fviernau requested changes

2021-09-13 11:31 UTC, fviernau commented on reporter-web-app/src/components/IssuesTable.js
> +            sortedInfo =  {}
commit message: 

support -> supports
React object -> React objects

maybe also:
sort enabled -> sorting enabled

2021-09-13 11:31 UTC, fviernau commented on reporter-web-app/src/components/RuleViolationsTable.js
> +                    if (webAppPackage) {
Could this be simplified as follows? (maybe it's out of scope of this commit)
```
onFilter: (value, webAppRuleViolation) => {
  const webAppPackage = webAppRuleViolation.package;
  const isExcluded = webAppPackage && webAppPackage.isExcluded

  return value === 'excluded' ?: isExcluded : !isExcluded
}
```

or

```
onFilter: (value, webAppRuleViolation) => {
  if (!webAppRuleViolation.hasPackage) return false

  const isExcluded = webAppRuleViolation.package.isExcluded

  return isExcluded && value === 'excluded' || !isExcluded && value === 'included'
}
```

2021-09-16 10:11 UTC, fviernau submitted a review, later dismissed

2021-09-16 10:11 UTC, fviernau commented on reporter-web-app/src/components/RuleViolationsTable.js
> +                    if (webAppPackage) {
Has been implemented in a separate commit on top.

2021-09-16 13:13 UTC, sschuberth commented on reporter-web-app/src/components/PackageDetails.js
> +    const {
Commit message nits: s/reporter-webapp/reporter-web-app/

Can you also briefly explain how it was before, if not for each package?

2021-09-16 13:15 UTC, sschuberth commented on reporter-web-app/src/components/IssuesTable.js
> +            state: {
Commit message nit: s/compacter/more compact/

2021-09-16 13:16 UTC, sschuberth commented on reporter-web-app/src/components/PackageDetails.js
> +                && vcsRevision !== vcsProcessedRevision
Commit message nit: Double space in "display  package's"

2021-09-17 10:43 UTC, fviernau approved these changes

2021-09-17 10:58 UTC, sschuberth approved these changes
Approving despite my comments to move things forward.

2021-09-17 10:58 UTC, sschuberth commented on reporter-web-app/src/components/PackageDetails.js
> +    const {
I don't see this being addressed in the commit message.

2021-09-17 10:58 UTC, sschuberth commented on reporter-web-app/src/App.css
> +    color: #84b6eb;
Nit: Existing code uses uppercase hex chars.

2021-09-17 10:58 UTC, sschuberth commented on reporter-web-app/src/components/RuleViolationsTable.js
> +                    if (!webAppRuleViolation.hasPackage()) return true;
Explaining the purpose of the refactoring in the commit message would be nice.

2021-09-17 11:06 UTC, merged