FossId: Set file name of pending identification as message
oss-review-toolkit/ort pull request #4482
Opened 2021-09-20 16:27 UTC by MarcelBochtler

See commit messages

2021-09-20 16:40 UTC, sschuberth requested changes

2021-09-20 16:40 UTC, sschuberth commented on scanner/src/test/kotlin/scanners/fossid/FossIdTest.kt
> +                    createPendingFile(4),
How about calling `createPendingFile(X)` for each `X` only once, like

    val expectedIssues = listOf(createPendingFile(4), createPendingFile(5)).map {
        OrtIssue(Instant.EPOCH, $it, "Pending identification for '$it'.", Severity.HINT)
    }

2021-09-21 05:34 UTC, sschuberth approved these changes

2021-09-21 07:52 UTC, nnobelis approved these changes

2021-09-21 08:03 UTC, merged