scanner: Add a parser for SCANOSS results
oss-review-toolkit/ort pull request #4597
Opened 2021-10-15 09:27 UTC by sschuberth

SCANNOSS [1] is a snippet scanner whose engine [2], mining tool [3] and
some other parts are Open Source. It also provides a public database of
"fingerprints" for Open Source packages [4]. As such it is a good fit
for being added to ORT as a supported scanner. This commit prepares for
that by adding a parser for SCANOSS results. More changes that trigger
the actualy scans and extensions to the ORT data model to capture
snippet findings [5] will follow later.

The license name is an SPDX ID, or "NOASSERTION" when there is an
exceptional situation.

[1]: https://scanoss.com/
[2]: https://github.com/scanoss/engine
[3]: https://github.com/scanoss/minr
[4]: https://osskb.org/
[5]: https://github.com/oss-review-toolkit/ort/issues/3265

Signed-off-by: Juan M Salamanca <juan.m.salamanca@scanoss.com>
Signed-off-by: Sebastian Schuberth <sebastian.schuberth@bosch.io>

2021-10-15 09:30 UTC, sschuberth commented
This is a preparation for adding SCANOSS as a scanner.

2021-11-01 15:32 UTC, sschuberth commented on scanner/src/main/kotlin/scanners/scanoss/ScanOssResultParser.kt
> +        copyrightFindings = getCopyrightFindings(result).toSortedSet(),
Done.

2021-11-02 16:02 UTC, mnonnenmacher requested changes

2021-11-02 16:29 UTC, mnonnenmacher approved these changes

2021-11-02 17:51 UTC, merged