Add JSON schema for .ort.yml configuration
oss-review-toolkit/ort pull request #4639
Opened 2021-10-29 11:30 UTC by MarcelBochtler

A JSON schema [1] is a description of a JSON document, which can also be
used for YAML files. This schema can be used to enable auto-completion
in multiple editors for the .ort.yml file [2]. E.g. IntelliJ IDEA has build-in support
for it [3]:
![Screenshot 2021-10-29 at 11 21 44](https://user-images.githubusercontent.com/4022103/139412824-1cf09a55-eb4a-40a1-8c38-bd5a00250948.png)

As a next step, the URL to this schema can be contributed to https://github.com/schemastore/schemastore/ and many editors will then have autocompletion for .ort.yml out of the box.

It would be nice to autogenerate this file, however I didn't find a convenient way to do this.
Adding the test coverage to avoid regressions in the schema should be good enough for now.

Missing as of now is the documentation from the model classes. It would be nice to also get this documentation during auto completion.

I opted to use the JSON format instead of a YAML format, to ensure better compatibility. I was e.g. not able to use a YAML schema with VS Code.

[1]: https://json-schema.org
[2]: https://www.schemastore.org/json
[3]: https://www.jetbrains.com/help/ruby/yaml.html#remote_json

2021-10-29 21:43 UTC, MarcelBochtler commented
> > It would be nice to autogenerate this file, however I didn't find a convenient way to do this.
> 
> Would you mind listing the tool you looked at? For example, did you try https://github.com/FasterXML/jackson-module-jsonSchema?

I tried https://github.com/mbknor/mbknor-jackson-jsonSchema.
This has some nice options to manipulate the generated schema, which might be handy to have. However, it has issues with the `required` option. [It uses nullable types](https://github.com/mbknor/mbknor-jackson-jsonSchema#code---using-java) to find the required parameters. As in ORT's models the fields are not nullable they are all generated as required.
I didn't find a way to work around this issue. (manually setting the parameters as not required [does also not work](https://github.com/mbknor/mbknor-jackson-jsonSchema/issues/142))

I also tried your linked https://github.com/FasterXML/jackson-module-jsonSchema.
Unfortunately the generate schema was not valid, or at least it was not usable within VS Code:
```
Problems loading reference 'urn:jsonschema/%3Aorg%3Aossreviewtoolkit%3Autils%3Aspdx%3Amodel%3ALicenseChoice': Unable to load schema from 'urn:jsonschema/%3Aorg%3Aossreviewtoolkit%3Autils%3Aspdx%3Amodel%3ALicenseChoice': No content.
```
And the `required` option is also not controllable and does not generate the correct scheme for the `RepositoryConfiguration`.

2021-10-30 19:55 UTC, sschuberth requested changes

2021-10-30 19:55 UTC, sschuberth commented on .reuse/dep5
> +Files: integrations/schemas/*
Commit message nits:
- I think it's fine / better to drop the "JSON-schema" prefix; we usually use these prefixes to denote which *existing* code is touched, but here the code does not exist yet. And the part after ":" also talks about "JSON schema".
- - [3] links to RubyMine docs. Probably https://www.jetbrains.com/help/idea/json.html#ws_json_schema_add_custom is better.

2021-11-01 06:33 UTC, sschuberth approved these changes

2021-11-01 17:26 UTC, merged