Apply VCS curation to `vcsProcessed` instead of to `vcs`
oss-review-toolkit/ort pull request #4653
Opened 2021-11-03 10:53 UTC by fviernau

2021-11-04 10:48 UTC, fviernau commented
@sschuberth @mnonnenmacher @tsteenbe I'm aware we discussed the `normalize()` should be dropped. However, I had further doubts that this is a good idea. As-is vcsProcessed is always normalized, which simplifies things and I don't see the reason why to drop that simplification. E.g. the downloader would need to apply normalization before downloading and also the matching of package configurations need to adhere to the fact that URLs are not normalized anymore. I guess that also the scan storage would be affected. No, matter what we decide about dropping the normalization. I believe it should be done out of scope of this PR.

2021-11-05 11:03 UTC, mnonnenmacher requested changes

2021-11-05 11:03 UTC, mnonnenmacher commented on model/src/main/kotlin/PackageCurationData.kt
> +    } ?: base.vcsProcessed
I think in line 132 below `vcs` now needs to stay unchanged and `vcsProcessed` needs to be set instead. This way `vcs` still represents the unmodified metadata of the package.

2021-11-05 11:03 UTC, mnonnenmacher commented on analyzer/src/funTest/assets/projects/synthetic/gradle-all-dependencies-expected-result-with-curations.yml
> +          url: "ssh://git@github.com/hamcrest/JavaHamcrest.git"
Commit message: Typo in `Package.vcsProcess`

2021-11-05 11:07 UTC, mnonnenmacher commented
> 
> 
> @sschuberth @mnonnenmacher @tsteenbe I'm aware we discussed the `normalize()` should be dropped. However, I had further doubts that this is a good idea. As-is vcsProcessed is always normalized, which simplifies things. E.g. the downloader would need to apply normalization before downloading and also the matching of package configurations need to adhere to the fact that URLs are not normalized anymore. Not sure what handling in the scan storage would be affected. Given these worries I prefer to not drop normalization.
> 
> No, matter what we decide at the end. I believe dropping normalization should be done out of scope of this PR, if at all.

IMO not normalizing curations is still the right idea but I understand that there is some migration effort involved as you describe, so I'm fine with doing it separately. To estimate the migration effort you could write a small function that goes through the curations and package configurations to check how many of them would be affected, maybe it's not that bad after all.

2021-11-05 13:47 UTC, mnonnenmacher approved these changes

2021-11-05 13:55 UTC, sschuberth commented on model/src/main/kotlin/Package.kt
> +     * [vcs], guessed from additional data as fallback or empty.
"[...] as *a* fallback, or empty."

2021-11-05 14:25 UTC, sschuberth commented on model/src/main/kotlin/Package.kt
> +     * [vcs], guessed from additional data as fallback or empty. On top of that [PackageCuration]s may have been
The commit message should fix https://github.com/oss-review-toolkit/ort/issues/4618.

2021-11-05 14:42 UTC, sschuberth approved these changes

2021-11-08 09:07 UTC, merged