#4699: analyzer/npm :: Add usage of --ignore-scripts parameter to "npm ci" in order to prevent unnecessary and risky script execution
oss-review-toolkit/ort pull request #4700
Opened 2021-11-15 11:14 UTC by rockebee

PR attempts to use `--ignore-scripts` parameter also in `npm ci` cases, not only for `npm install`.
(cmp. #4699 for respective issue description)

2021-11-16 15:25 UTC, mnonnenmacher requested changes
@rockebee Thank you for the contribution. Please sign your commit message (see the failing DCO check) and reformat it to match our standards, for example like so:

```
Npm: Add `--ignore-scripts` to `npm ci`

Add usage of `--ignore-scripts` to the `npm ci` call in order to prevent
unnecessary and risky script execution.

Fixes #4699.
```

2021-11-16 15:31 UTC, sschuberth commented
Quoting @rockebee from #4699:

> Caveat: `ignore-scripts` was introduced with NPM 5.7.0 (together with `npm ci` itself), but was not supported in NPM versions 7.0.0 < 7.4.0 ([link](https://github.com/npm/cli/pull/2455))

So, should we change the code to only pass `--ignore-scripts` to `npm ci` for version 5.7.0 to 7.0.0, or versions above 7.4.0?

2021-11-16 17:00 UTC, mnonnenmacher commented
> 
> 
> Quoting @rockebee from #4699:
> 
> > Caveat: `ignore-scripts` was introduced with NPM 5.7.0 (together with `npm ci` itself), but was not supported in NPM versions 7.0.0 < 7.4.0 ([link](https://github.com/npm/cli/pull/2455))
> 
> So, should we change the code to only pass `--ignore-scripts` to `npm ci` for version 5.7.0 to 7.0.0, or versions above 7.4.0?

I understood the PR so that the option was still present but simply not working from 7.0.0-7.4.0.

2021-11-16 19:40 UTC, sschuberth commented
> I understood the PR so that the option was still present but simply not working from 7.0.0-7.4.0.

Ah, ok. Then of course the code should be fine as-is.

2021-11-17 12:09 UTC, rockebee commented
@mnonnenmacher @sschuberth, thx for feedback. Commit message is now signed properly and commit message modified as suggested.
I agree that IMHO there is no need to exclude NPM versions 7.0.0 to < 7.4.0, as `npm ci` itself is properly working, just the `--ignore-scripts` flag was not working and ignored.

2021-11-17 13:53 UTC, sschuberth commented
Nit: There needs to be a blank line between

    Fixes #4699.
    Signed-off-by: Stefan Schwenkenbecher <38685542+rockebee@users.noreply.github.com>

to separate the body from the footer.

2021-11-17 16:40 UTC, sschuberth approved these changes

2021-11-17 16:40 UTC, merged