CreateAnalyzerResultCommand: Add the parameter `--scan-code-version`
oss-review-toolkit/ort pull request #4742
Opened 2021-11-23 20:10 UTC by fviernau

Allow to narrow down the matching of scan result entries in the postgres
storage to a given ScanCode version.

This enables the use case to re-scan a given set of package IDs which
have been scanned before with the specified ScanCode version.

2021-11-23 20:32 UTC, sschuberth commented on helper-cli/src/main/kotlin/commands/CreateAnalyzerResultCommand.kt
> +        "--scan-code-version",
How about naming this `--scancode-version`, like the `scancode` CLI?

2021-11-23 20:32 UTC, sschuberth commented on helper-cli/src/main/kotlin/commands/CreateAnalyzerResultCommand.kt
> +        help = "The scan code version to match for equality against the scan results."
s/scan code/ScanCode/

2021-11-23 20:32 UTC, sschuberth commented on helper-cli/src/main/kotlin/commands/CreateAnalyzerResultCommand.kt
> +        help = "The scan code version to match for equality against the scan results."
Also "to match for equality against" sounds a bit clumsy... how about just "to match for in the scan results"?

2021-11-23 20:32 UTC, sschuberth commented on helper-cli/src/main/kotlin/commands/CreateAnalyzerResultCommand.kt
> +            ${ scanCodeVersion?.let { "s.scan_result->'scanner'->>'version' = '$it' AND" }.orEmpty() }
Just an idea (typing blindly):

    val whereClause = listOfNotNull(
        scanCodeVersion?.let { "s.scan_result->'scanner'->>'version' = '$it'",
        "s.identifier = ANY(?)"
    ).joinToString(" AND ")

    // ....

    WHERE $whereClause;

2021-11-24 06:39 UTC, sschuberth commented on helper-cli/src/main/kotlin/commands/CreateAnalyzerResultCommand.kt
> +        "--scan-code-version",
The commit message title still has `--scan-code-version`.

2021-11-24 06:40 UTC, sschuberth commented
PS: A failing test will be fixed by my https://github.com/oss-review-toolkit/ort/pull/4743/commits/42f090d884e0e6b798968ac0d8ad9a5fa79f877e.

2021-11-24 06:41 UTC, sschuberth commented on helper-cli/src/main/kotlin/commands/CreateAnalyzerResultCommand.kt
> +        scanCodeVersion?.let { "s.scan_result->'scanner'->>'version' = '$it'" },
Nit: Please remove the trailing comma.

2021-11-24 08:06 UTC, sschuberth submitted a review, later dismissed

2021-11-26 17:44 UTC, sschuberth approved these changes

2021-11-26 17:45 UTC, sschuberth requested changes
Is that the right commit on that branch? It seems to mismatch the PR title at least...

2021-11-26 17:47 UTC, fviernau commented
> Is that the right commit on that branch? It seems to mismatch the PR title at least...

Good catch, it was not the right one.

2021-11-26 17:49 UTC, sschuberth approved these changes

2021-11-29 10:08 UTC, merged

2021-11-29 10:08 UTC, fviernau commented
Merged despite failing unrelated tests.