fossid-webapp: Compatibility with FossID 2021.2.3
oss-review-toolkit/ort pull request #4795
Opened 2021-12-02 14:26 UTC by nnobelis

Adapt the FossID scanner to be compatible with the latest version of
FossID. Compatibility with previous versions is preserved.
The only changes impacting ORT are the ones made to the [Project] model
class.

List of relevant changes:
projects - get_information
  * Response no longer has the keys 0 - 14 included that duplicates the
  information of the named keys.
  * Response datatype of project id changed from string to integer
  * Response datatype of creator value changed from string to integer
  * Response datatype of is_archived value changed from string to
  integer

Signed-off-by: Nicolas Nobelis <nicolas.nobelis@bosch.io>

2021-12-02 14:39 UTC, nnobelis commented
Just a sidenote: this change is not mandatory because our current codebase is already compatible with FossID 2021.2.3.
However, the changes in this PR allow to have a 100% correct representation of the entities returned by this FossID version.

2021-12-02 14:49 UTC, sschuberth requested changes

2021-12-02 14:49 UTC, sschuberth commented on clients/fossid-webapp/src/main/kotlin/VersionedFossIdService2021dot2.kt
> +    override suspend fun getProject(
Please add a blank line before this one.

2021-12-02 14:49 UTC, sschuberth commented on clients/fossid-webapp/src/main/kotlin/FossIdServiceWithVersion.kt
> +    ): EntityResponseBody<out UnversionedProject>
Broken formatting.

2021-12-02 14:49 UTC, sschuberth commented on clients/fossid-webapp/src/main/kotlin/model/UnversionedProject.kt
> +interface UnversionedProject {
Could you please separate out some independent preparations, like the introduction of this interface, to preceding commits?

2021-12-08 11:03 UTC, nnobelis commented
DO NOT MERGE: FossID are rolling back some of their changes.
Let's wait a little what is coming out from the discussions between FossID and the new version early adopters.

2022-01-07 13:47 UTC, sschuberth commented
I'm moving this back to draft state to signal this should not yet be merged.

2022-07-14 12:08 UTC, closed without merging