Auto-completion for the Evaluator rules example
oss-review-toolkit/ort pull request #4921
Opened 2022-01-06 13:48 UTC by sschuberth

Please have a look at the individual commit messages for the details.

2022-01-06 16:12 UTC, mnonnenmacher requested changes

2022-01-06 16:12 UTC, mnonnenmacher commented on README.md
> +well. See [example.rules.kts](./examples/evaluator-rules/src/main/resources/example.rules.kts) for an example file.
While on it you could also fix that the brace in the line above is never closed, and more importantly, mention that code completion for this file is supported and also link to the "evaluator-rules" example project. But the latter is probably better done in `file-rules-kts.md` which you also edit below.

2022-01-06 20:07 UTC, mnonnenmacher approved these changes

2022-01-07 13:35 UTC, sschuberth commented
Merging despite the unrelated test failures.

2022-01-07 13:36 UTC, merged