Implement auto-completion support for Notifier scripts
oss-review-toolkit/ort pull request #4960
Opened 2022-01-14 16:11 UTC by sschuberth

Please have a look at the individual commit messages for the details.

2022-01-15 14:06 UTC, tsteenbe reviewed
@sschuberth  Am I right this auto-completion works similar to how you changed rules.kts, if you then shouldn't this PR also update https://github.com/oss-review-toolkit/ort/blob/master/examples/notifications.kts?

2022-01-15 14:09 UTC, sschuberth commented
Yes, I'll also update the example once the details of this PR (like the chosen double-extension of notification scripts) are set. But I'll do this separately as this PR already has 8 commits.

2022-01-15 15:35 UTC, sschuberth commented
> But I'll do this separately as this PR already has 8 commits.

Ok, I changed my mind an added 2 additional commits as I had to make a fixup anyway.

2022-01-17 20:39 UTC, mnonnenmacher requested changes

2022-01-17 20:39 UTC, mnonnenmacher commented on README.md
> +  [emails](./examples/notifications/src/main/resources/example.notifications.kts) and / or JIRA tickets).
Commit message typo: "zu" -> "to"

2022-01-17 20:42 UTC, sschuberth commented on README.md
> +  [emails](./examples/notifications/src/main/resources/example.notifications.kts) and / or JIRA tickets).
Fixed.

2022-01-17 20:43 UTC, mnonnenmacher commented
> Yes, I'll also update the example once the details of this PR (like the chosen double-extension of notification scripts) are set.

I do agree with the chosen name.

2022-01-17 20:43 UTC, mnonnenmacher approved these changes

2022-01-17 20:47 UTC, sschuberth commented
> I do agree with the chosen name.

I was considering to rather use `*.<toolname>.kts`, like `*.evaluator.kts` instead of `*.rules.kts`. That would al least "scale" if more tools got scripting. On the other hand it would get difficult again once a single tool supports multiple types of scripts...

2022-01-18 07:41 UTC, merged