Create github action to build and upload Docker image
oss-review-toolkit/ort pull request #5015
Opened 2022-02-01 21:03 UTC by andreasdotorg

This github action builds a Docker image from the ort source, and uploads it to the github Docker container registry. This allows users to run ort by simply installing from the container registry with a one liner like:

$ docker pull ghcr.io/oss-review-toolkit/ort:master

and then running it via

$ docker run ort

Signed-off-by: Andreas Bogk <andreas@andreas.org>

2022-02-02 16:57 UTC, MarcelBochtler commented
Thanks for your contribution @andreasdotorg.
Please be aware of [the discussion about releasing a public ORT image](https://github.com/oss-review-toolkit/ort/issues/2441).
Specifically, [this comment](https://github.com/oss-review-toolkit/ort/issues/2441#issuecomment-774483931) from @tsteenbe.

The ORT steering team @oss-review-toolkit/core-devs would need to decide what is required (from a non-technical point of view) to publish such an image.

2022-02-04 22:27 UTC, andreasdotorg commented
I understand and appreciate the concerns. I might be back with a solution or not.

2022-02-05 20:54 UTC, sschuberth requested changes

2022-02-05 20:54 UTC, sschuberth commented on .github/workflows/build-and-upload-docker.yml
> +          submodules: recursive
That shouldn't be necessary as we use Git submodules exclusively for referring to external functional test projects.

2022-02-05 20:54 UTC, sschuberth commented on .github/workflows/build-and-upload-docker.yml
> +        if: github.event_name != 'pull_request'
Is this really necessary as the `on:` above does *not* contain `pull_request:`?

2022-02-05 20:55 UTC, sschuberth commented
BTW, nice to meet you again, @andreasdotorg 😃

2022-02-05 21:04 UTC, tsteenbe commented
Great to see a familiar face @andreasdotorg, are you using ORT just personally or at work?

2023-11-20 07:07 UTC, sschuberth commented
This has been superseded by https://github.com/oss-review-toolkit/ort/pull/7474.

2023-11-20 07:07 UTC, closed without merging