Features/tekton example
oss-review-toolkit/ort pull request #5185
Opened 2022-03-23 11:14 UTC by cgrotz

This PR contains an example how to run ORT on K8S clusters using Tekton. I would highly appreciate some feedback!

2022-03-23 22:17 UTC, sschuberth commented
Thanks a lot for this @cgrotz! Before starting the real review, could you please get rid of the merge commit in the PR, and rather *rebase* onto latest `main`?

2022-03-24 07:36 UTC, cgrotz commented
> Thanks a lot for this @cgrotz! Before starting the real review, could you please get rid of the merge commit in the PR, and rather _rebase_ onto latest `main`?

Sure, the GitHub `Fetch Upstream` feature got me there. Should be fixed now.

2022-03-24 07:53 UTC, sschuberth requested changes
Just a bunch of docs nits 😁

2022-03-24 07:53 UTC, sschuberth commented on integrations/tekton/README.md
> +This example pipeline allows you to easily run an ORT scan on [Tekton](https://tekton.dev/), some knowledge about Tekton will help to understand this example pipeline.. This example pipeline works be
- Maybe just "run ORT on"?
- Start a new sentence from "Some knowledge..."?
- s/pipeline../pipeline./
- It is really true that this "works best" on GKE, or has it only been tested on GKE? If indeed the former, could you briefly add why?

2022-03-24 07:53 UTC, sschuberth commented on integrations/tekton/README.md
> +To run the pipeline, you will need the following things:
Nit: Please add a blank line after the title for readability, like above.

2022-03-24 07:53 UTC, sschuberth commented on integrations/tekton/README.md
> +* A Kubernetes Cluster with Tekton installed (follow the [installation instructions](https://tekton.dev/docs/pipelines/install/))
- s/Cluster/cluster
- In general, please also end sentences from bullet lists with a dot (also in lists below).

2022-03-24 07:53 UTC, sschuberth commented on integrations/tekton/README.md
> +The pipeline definition is in the `ort-pipeline.yaml` you will need to replace `ort:latest` with the full image name e.g. `gcr.io/<project_id>/ort:latest`.
Maybe: "The pipeline is defined in `ort-pipeline.yaml`. You will..."

Comma before "e.g.".

2022-03-24 07:53 UTC, sschuberth commented on integrations/tekton/README.md
> +This example pipeline allows you to easily run an ORT scan on [Tekton](https://tekton.dev/), some knowledge about Tekton will help to understand this example pipeline.. This example pipeline works be
Also, we should probably explain acronyms once before using them later, like

[Google Kubernetes Engine](https://cloud.google.com/kubernetes-engine) (GKE)

2022-03-24 07:53 UTC, sschuberth commented on integrations/tekton/README.md
> +* A [Google Cloud Storage](https://cloud.google.com/products/storage) bucket
Also explain acronym here for later use: [Google Cloud Storage](https://cloud.google.com/products/storage) (GCS)

2022-03-24 07:53 UTC, sschuberth commented on integrations/tekton/README.md
> +* `gcs-credentials` is a workspace and will need a volume. On GKE you can use Workload Identities to allow the KSA to access the GCS bucket for uploading the results. (If you are not using Workload I
What's KSA?

2022-03-24 07:53 UTC, sschuberth commented on integrations/tekton/README.md
> +* `repo-url` is a param, and takes the path to the Git repo that should be scanned
s/param/parameter/

(Unless "param" really is a coined term here. Same below.)

2022-03-24 07:53 UTC, sschuberth commented on integrations/tekton/README.md
> +In order to get started call `kubectl apply -f ort-pipeline.yaml` to create the pipeline on your Kubernetes cluster. Now, if you want to trigger a pipeline run, you need to create a `PipelineRun` res
Comma before "you can call".

2022-03-24 07:53 UTC, sschuberth commented on integrations/tekton/README.md
> +![Example run of Simple Maven](imgs/simple-maven.png)
Let's name the directory "images".

2022-03-24 07:53 UTC, sschuberth commented on integrations/tekton/README.md
> +You probably don't want to trigger each execution via kubectl. Checkout the [Tekton documentation](https://tekton.dev/docs/triggers/) to learn how you can trigger a PipelineRun via EventListeneres.
- s/kubectl/`kubectl`/
- s/Checkout/Check out/
- Probably "PipelineRun" and "EventListeneres" should be formatted to stand out, maybe like *PipelineRun* and *EventListeneres*.

2022-03-24 07:53 UTC, sschuberth commented on integrations/tekton/README.md
> +If you aren't working on a public GitHub repo you should also checkout how to work with a [private repo](https://hub.tekton.dev/tekton/task/git-clone).
Spell out "repo" as "repository".

2022-03-24 07:53 UTC, sschuberth commented on integrations/tekton/mime-types.yaml
> +    value: gs://ort-tekton/reports
Missing final newline.

2022-03-24 07:53 UTC, sschuberth commented on integrations/tekton/simple-maven.yaml
> +    value: gs://ort-tekton/reports
Missing final newline.

2022-03-25 17:10 UTC, sschuberth commented
Thanks @cgrotz for the updates! Please squash all commits into one, as we prefer to have review comments addressed in the commits they belong to.

Also, we follow Git's convention for writing commit messages, so please use [imperative mood](https://github.com/oss-review-toolkit/.github/blob/main/CONTRIBUTING.md#git-history), i.e. instead of "Created ..." say "Create ...".

2022-03-25 17:11 UTC, sschuberth commented
Also the REUSE check fails, because your newly added files need to be explicitly licensed via entries in the `.reuse/dep5` file.

2022-04-12 09:59 UTC, sschuberth approved these changes

2022-04-12 10:00 UTC, sschuberth commented
Merging despite the unrelated `ConanFunTest` failure.

2022-04-12 10:00 UTC, merged