PackageConfiguration: Support matching any `revision`
oss-review-toolkit/ort pull request #5233
Opened 2022-04-06 17:40 UTC by sschuberth

Please have a look at the individual commit messages for the details.

2022-04-06 17:45 UTC, sschuberth commented
@fviernau, after another discussion with @mnonnenmacher we decided to propose this change *without* hiding it behind a feature toggle. The reason mostly is that any such conventions like requiring a fixed `revision` could (and probably should) be implemented via CI checks on package configuration changes. That way, we avoid an increasing number of feature toggles being introduced, esp. before have a proper mechanism to share global configuration throughout all of ORT without passing config options everywhere.

So, what do you think @fviernau?

2022-04-06 20:31 UTC, mnonnenmacher requested changes

2022-04-06 20:31 UTC, mnonnenmacher commented on model/src/main/kotlin/config/PackageConfiguration.kt
> +    val revision: String? = null
Please also update `docs/config-file-package-configuration-yml.md`, maybe just add "(optional)" before the one mention of the revision property.

2022-04-07 07:09 UTC, mnonnenmacher approved these changes

2022-04-07 08:34 UTC, tsteenbe approved these changes

2022-04-07 10:03 UTC, merged