PubCacheReader: Fix handling of Git dependencies
oss-review-toolkit/ort pull request #5292
Opened 2022-04-27 15:48 UTC by MarcelBochtler

The `packageInfo` for Pub's Git dependencies contain different
information as for hosted dependencies. Fix the path construction for
dependency resolution from Pub's cache.

Resolves #5196.

2022-04-27 16:29 UTC, sschuberth commented
> contain different information as

contains different information than

2022-04-28 07:36 UTC, sschuberth requested changes

2022-04-28 07:36 UTC, sschuberth commented on analyzer/src/test/kotlin/managers/utils/PubCacheReaderTest.kt
> +        }
Can we instead make `PubCacheReader.pubCacheRoot` `internal` and use it?

2022-04-28 07:36 UTC, sschuberth commented on analyzer/src/test/kotlin/managers/utils/PubCacheReaderTest.kt
> +            .also { it.mkdirs() }
Maybe better use `safeMkdirs()`? Same below.

2022-04-28 07:40 UTC, MarcelBochtler commented on analyzer/src/test/kotlin/managers/utils/PubCacheReaderTest.kt
> +        println(hostedPackageCacheDir)
Sorry debug leftover :)

2022-04-28 07:55 UTC, MarcelBochtler commented on analyzer/src/test/kotlin/managers/utils/PubCacheReaderTest.kt
> +        hostedPackageCacheDir.parentFile.deleteRecursively()
To do that, I would need a possibility to adjust the `PubCacheReader.pubCacheRoot` in the production code. Do you think this is worth the effort?

2022-04-28 09:11 UTC, sschuberth commented on analyzer/src/test/kotlin/managers/utils/PubCacheReaderTest.kt
> +        hostedPackageCacheDir.parentFile.deleteRecursively()
Nope, probably not.

2022-04-28 09:36 UTC, MarcelBochtler commented on analyzer/src/test/kotlin/managers/utils/PubCacheReaderTest.kt
> +        hostedPackageCacheDir.parentFile.deleteRecursively()
Done.

2022-04-28 09:41 UTC, sschuberth requested changes

2022-04-28 09:41 UTC, sschuberth commented on analyzer/src/test/kotlin/managers/utils/PubCacheReaderTest.kt
> +        tmpPubCacheDir.resolve("hosted/oss-review-toolkit.org/$PACKAGE_NAME-$PACKAGE_VERSION")
If I didn't count wrong, this should actually fit into a single line.

2022-04-28 09:41 UTC, sschuberth commented on analyzer/src/test/kotlin/managers/utils/PubCacheReaderTest.kt
> +    }
This is not needed anymore with `createSpecTempDir`.

2022-04-28 09:41 UTC, sschuberth commented on analyzer/src/test/kotlin/managers/utils/PubCacheReaderTest.kt
> +        // Prepare expected cache directories.
Is this comment still valuable?

2022-04-28 09:50 UTC, sschuberth approved these changes

2022-04-28 10:42 UTC, merged