.mailmap: Add Thomas' e-mail addresses
oss-review-toolkit/ort pull request #5422
Opened 2022-06-09 11:21 UTC by fviernau

Add his new e-mail address at EPAM and also cover all his addresses
present in the Git log.

2022-06-09 11:21 UTC, fviernau commented
@tsteenbe I just updated mine and while at it did this - please confirm it's ok.

2022-06-09 11:26 UTC, sschuberth requested changes

2022-06-09 11:26 UTC, sschuberth commented on .mailmap
> +Thomas Steenbergen <thomas_steenbergen@epam.com> <thomas_steenbergen@here.com>
The HERE email address should say `<thomas.steenbergen@here.com>` (with a dot instead of an underscore).

2022-06-10 09:27 UTC, tsteenbe approved these changes

2022-06-10 09:27 UTC, merged