Add NOTICE file
oss-review-toolkit/ort pull request #5472
Opened 2022-06-21 13:17 UTC by MarcelBochtler

The copyright list for the NOTICE file was compiled with a combination of plain text search and manually from the [dep5](https://github.com/oss-review-toolkit/ort/blob/main/.reuse/dep5) file.

Command used for [ripgrep](https://github.com/BurntSushi/ripgrep):
```
rg --hidden --no-filename --no-line-number --iglob \!utils/spdx/src/main/resources/licenses/ 'Copyright \(C\)' | sort | uniq
```

I also tried to compile the list using ORT itself:
```
ort --info scan --package-types PROJECT -i ort/analyzer-result.yml -o ort/
```

This resulted in a list which is too large, and would require quite some exclusions in the `.ort.yml`.
```
❯ grep 'statement:' scan-result.yml | sort | uniq | wc -l
1746
```

2022-06-21 13:29 UTC, mnonnenmacher requested changes

2022-06-21 14:02 UTC, sschuberth commented on NOTICE
> +Copyright (C) 2007-2020 The original author or authors <info@gradle.com>
But [the plan](https://github.com/oss-review-toolkit/ort-governance/issues/6#issuecomment-1117175813) is to refer to the `NOTICE` file for the detailed list of Copyright holders of ORT, and the Gradle authors are *not* Copyright holders on ORT. So keeping Gradle in here would be highly misleading, IMO.

2022-06-21 14:04 UTC, sschuberth commented on NOTICE
> +Copyright (C) 2007-2020 The original author or authors <info@gradle.com>
Maybe that's after all [another argument](https://github.com/oss-review-toolkit/ort-governance/issues/6#issuecomment-1160176834) for not using a `NOTICE` file, but an `AUTHORS` file, to make more clear that only authors of ORT are listed, and not some other assembled Copyright holders.

2022-06-21 14:05 UTC, sschuberth commented on NOTICE
> +Copyright (C) 2022 Google, LLC.
IMO we shouldn't. Simply keep alphabetical sorting here to be able to easily create the file automatically one day. Emphasizing who the main contributors are should IMO be done differently, e.g. via company logos in the `README.md`.

2022-06-21 14:24 UTC, sschuberth commented on NOTICE
> +Copyright (C) 2007-2020 The original author or authors <info@gradle.com>
> What about JetBrains which comes from this copyright statement?

I believe that's formally correct as I copied (small) parts of that file from JetBrains' example code.

2022-06-27 08:21 UTC, fviernau requested changes

2022-07-04 08:20 UTC, tsteenbe commented on NOTICE
> +Copyright (C) 2022 Google, LLC.
Change "The ORT Project" to "The ORT Project <https://oss-review-toolkit.org> to help promote the project.

2022-07-15 08:38 UTC, MarcelBochtler commented
@oss-review-toolkit/core-devs
Can we move on with this change? Any blockers you see?

2022-07-18 05:53 UTC, sschuberth commented
> Can we move on with this change? Any blockers you see?

I believe you didn't address @tsteenbe's [comment from here](https://github.com/oss-review-toolkit/ort/pull/5472/commits/bf17275f13096b6a569854387cbac9e7acbe2ced#r912748091) yet.

2022-07-18 05:59 UTC, sschuberth commented on NOTICE
> +Copyright (C) 2022 Google, LLC.
> Simply keep alphabetical sorting here to be able to easily create the file automatically one day.

Ok, so we [agreed on alphabetical ordering](https://github.com/oss-review-toolkit/ort-governance/pull/30/files#diff-c4e9232c368ba3b3e96e7103a1eb1f90a7c0c5aecf44d13a996802777597170eR12). However, the alphabetical order is mostly determined by the year (range), not by the company name, which is a bit disturbing.

So, as we also agreed to [only maintain the inception year](https://github.com/oss-review-toolkit/ort-governance/pull/30/files#diff-c4e9232c368ba3b3e96e7103a1eb1f90a7c0c5aecf44d13a996802777597170eR31) going forward, I was wondering whether we could already drop the upper bound of the year ranges from this file. It does not fully fix the "sort alphabetically by company name issue", but it makes the file a bit more aligned / readable.

2022-07-18 17:15 UTC, sschuberth approved these changes
IMO we can merge this now and eventually make any fix-ups later.

2022-08-11 16:39 UTC, mnonnenmacher approved these changes

2022-08-22 08:10 UTC, tsteenbe approved these changes

2022-08-22 12:45 UTC, fviernau approved these changes

2022-08-22 14:05 UTC, fviernau approved these changes

2022-08-22 14:21 UTC, merged