Jenkins subdirectory readme
oss-review-toolkit/ort pull request #5549
Opened 2022-07-13 09:45 UTC by sschuberth

Please have a look at the individual commit messages for the details.

2022-07-13 09:47 UTC, sschuberth commented
This might be a breaking change for users that refer to `integrations/Jenkinsfile` from this repo directly.

2022-07-13 19:05 UTC, fviernau requested changes

2022-07-14 06:19 UTC, fviernau approved these changes

2022-07-14 10:15 UTC, tsteenbe commented
@sschuberth  This PR does not seem like a breaking change to me... was it incorrectly labelled?

2022-07-14 10:19 UTC, sschuberth commented
> @sschuberth  This PR does not seem like a breaking change to me... was it incorrectly labelled?

Please see my comment above about that.

2022-07-14 12:34 UTC, merged