Package.diff() fixes
oss-review-toolkit/ort pull request #5638
Opened 2022-08-05 09:50 UTC by fviernau

See individual commits.

2022-08-05 13:30 UTC, MarcelBochtler approved these changes

2022-08-11 14:25 UTC, mnonnenmacher requested changes

2022-08-11 14:25 UTC, mnonnenmacher commented on model/src/main/kotlin/CuratedPackage.kt
> +            // It's not possible to derive the original concluded license value with the above reversed application
Nit: "It's" -> "It is"

2022-08-22 07:55 UTC, sschuberth commented on model/src/main/kotlin/CuratedPackage.kt
> +            // It is not possible to derive the original concluded license value with the above reversed application
Nit: Blank line before this one to group the comment with the belonging line of code.

2022-08-22 09:49 UTC, mnonnenmacher approved these changes

2022-08-22 09:50 UTC, merged