VcsInfo: Remove resolved revision
oss-review-toolkit/ort pull request #5817
Opened 2022-09-17 17:28 UTC by mnonnenmacher

Please see the commit messages for details.

2022-09-18 17:17 UTC, sschuberth commented on model/src/main/kotlin/VcsInfo.kt
> +            VcsInfo::class.memberProperties.map { PROPERTY_NAMING_STRATEGY.translate(it.name) }
BTW, do you remember why we introduced the check for unknown properties via `KNOWN_FIELDS`? Isn't it Jackson's default to fail on unknown properties if `@JsonIgnoreProperties(ignoreUnknown = true)` is not specified?

2022-09-18 17:17 UTC, sschuberth commented on model/src/main/kotlin/VcsInfo.kt
> +            type = type.takeUnless { it == EMPTY.type } ?: other.type,
Nit: The commit message could provide a rationale... is readability really and issue here, as each line already has the field name?

2022-09-18 17:17 UTC, sschuberth commented on model/src/test/kotlin/VcsInfoTest.kt
> +                knownPropertyIds should containAll<Any>("type", "url", "revision", "path")
Any idea why the test still passed? Again a Gradle task caching issue?

2022-09-18 17:54 UTC, sschuberth commented on model/src/test/kotlin/VcsInfoTest.kt
> +                knownPropertyIds should containAll<Any>("type", "url", "revision", "path")
Ah, scratch that, I had overlooked that `resolved_revision` was still present a few lines above in the test data.

2022-09-18 17:59 UTC, sschuberth commented on model/src/main/kotlin/VcsInfo.kt
> +            VcsInfo::class.memberProperties.map { PROPERTY_NAMING_STRATEGY.translate(it.name) }
I just verified that the `"fail if the input contains unknown fields"` test actually passes even if the `VcsInfoDeserializer` is removed. So maybe you could remove it completely as part of this PR?

2022-09-19 06:50 UTC, fviernau requested changes

2022-09-19 06:50 UTC, fviernau commented on model/src/main/kotlin/VcsInfo.kt
> +            node["revision"].textValueOrEmpty(),
Would it make sense to fail hard if user is still using the old (now unhandled) format? That would be nice, in particular if it was possible to remove the custom serializer as per @sschuberth 's comment above.

2022-09-20 07:11 UTC, sschuberth commented
@mnonnenmacher my proposal would be to drop "VcsInfo: Make KNOWN_FIELDS a set" (and maybe "VcsInfo: Use named arguments") from this PR, and then cherry-pick @fviernau's single commit from https://github.com/oss-review-toolkit/ort/pull/5827. That would make it nicely clear from the Git history why the custom deserializer can be removed.

2022-09-20 07:27 UTC, fviernau commented
> @mnonnenmacher my proposal would be to drop "VcsInfo: Make KNOWN_FIELDS a set" (and maybe "VcsInfo: Use named arguments") from this PR, and then cherry-pick @fviernau's single commit from #5827. That would make it nicely clear from the Git history why the custom deserializer can be removed.

@sschuberth, doesn't my commit message in #5827 not make it sufficiently clear? e.g. backwards compatibility for that time (first part of 2021) has been broken anyway by recent changes. Partial backwards compatibility is of no value as deserialization fails anyway. What am I missing?

2022-09-20 07:36 UTC, sschuberth commented
> What am I missing?

To me, @mnonnenmacher's `resolved_revision`-related commits in this PR are somewhat fixups / follow-ups to abd41579bd1e882870350dbcc7db781e22ec5c56 only, and having these committed separately nicely creates an intermediate state with

        val KNOWN_FIELDS by lazy {
            VcsInfo::class.memberProperties.map { PROPERTY_NAMING_STRATEGY.translate(it.name) }
        }

which makes it super-clear that there is no value in keeping the custom deserializer. This way the Git history simply tells a nicer story, IMO. But I'm also ok with just superseding this PR with yours, if @mnonnenmacher agrees.

2022-09-20 08:21 UTC, mnonnenmacher commented
@sschuberth @fviernau This change is not super urgent, why couldn't you just have waited a few days to give me a chance to respond to the initial code review instead of creating a separate PR and starting this discussion? I think this is just a waste of time for everyone involved.

With that being said, I think the reason for the custom deserializer was also to allow only a single value of `VcsInfo` while not providing default values in code. @fviernau Would this still work after your PR, e.g. to set only the VCS revision in a curation?

2022-09-20 08:28 UTC, fviernau commented
> @sschuberth @fviernau This change is not super urgent, why couldn't you just have waited a few days to give me a chance to respond to the initial code review instead of creating a separate PR and starting this discussion? I think this is just a waste of time for everyone involved.

That was unintended. When I created my PR I didn't recall that it overlaps with your PR. 
Only @sschuberth brought this to my attention. I decided to not close my PR, as in my view I could not see anything wrong with it and thought it could be merged as-is to save time for everyone involved in this discussion here. If that's not the case then let's just ditch my PR, as the last thing I wanted with this is wasting your time.

> With that being said, I think the reason for the custom deserializer was also to allow only a single value of `VcsInfo` while not providing default values in code. @fviernau Would this still work after your PR, e.g. to set only the VCS revision in a curation?

`PackageCurationData` is using `VcsInfoCurationData`, not `VcsInfo`. So, the requirement to work with not present values is not existing to my understanding. Am I missing something?

2022-09-20 09:20 UTC, mnonnenmacher commented
> `PackageCurationData` is using `VcsInfoCurationData`, not `VcsInfo`. So, the requirement (from curations) to work with absent values is not existing to my understanding. Am I missing something?

I just remembered that this was the initial reason for the deserializer, maybe it could already have been removed in 550e208 a long time ago. So yes, go ahead and merge your PR.

2022-09-20 20:13 UTC, mnonnenmacher commented
Obsolete with #5827.

2022-09-20 20:13 UTC, closed without merging