Drop support for legacy `hash` format
oss-review-toolkit/ort pull request #5819
Opened 2022-09-19 08:16 UTC by fviernau

The model for the `Hash` class has been changed in 2019.
Use the new format throughout the code base and drop handling of the legacy format to reduce technical debt.

2022-09-19 08:44 UTC, sschuberth requested changes

2022-09-19 08:44 UTC, sschuberth commented on integrations/schemas/curations-schema.json
> +              "hash",
I believe this commit should also drop the `"string"` type from https://github.com/oss-review-toolkit/ort/blob/ca7beff23342d5c1b9a2bdbaa6c79c9e6cadadeb/integrations/schemas/curations-schema.json#L133.

2022-09-19 08:59 UTC, sschuberth submitted a review, later dismissed

2022-09-19 09:19 UTC, fviernau commented
@oss-review-toolkit/bosch, @bennati is this ok to merge from Bosch and HERE side?

2022-09-19 09:46 UTC, nnobelis commented
> @oss-review-toolkit/bosch, @bennati is this ok to merge from Bosch and HERE side?

Hey @fviernau I found some usage of the old syntax by us. Let me fix them first please, I will then give you an heads-up.

2022-09-19 09:51 UTC, bennati commented
please go ahead

2022-09-19 09:56 UTC, fviernau commented
> Hey @fviernau I found some usage of the old syntax by us. Let me fix them first please, I will then give you an heads-up.

Thanks @nnobelis !

2022-09-19 21:27 UTC, mnonnenmacher approved these changes

2022-09-19 21:27 UTC, mnonnenmacher commented
@fviernau Fixes on our side are done.

2022-09-20 06:16 UTC, merged

2022-10-13 12:09 UTC, MarcelBochtler commented
Unfortunately, this breaks all projects, which use the legacy format in their `.ort.yml` :/

2022-10-13 12:18 UTC, MarcelBochtler commented
Additionally, the JsonSchema for the curations still shows the legacy format as valid.

2022-10-13 14:17 UTC, mnonnenmacher commented
I guess the problem is that the documentation was not updated long ago when the format was changed in 2019.