Conan: Do not log passwords
oss-review-toolkit/ort pull request #5873
Opened 2022-09-27 10:25 UTC by oheger-bosch

Since Conan uses `ProcessCapture` to run `conan user` commands, the whole command line including the password is logged. This PR adds a mechanism to mask specific arguments when using `ProcessCapture`, so that sensitive information can be hidden.

2022-09-27 10:38 UTC, sschuberth commented
I'm wondering whether that masking feature shouldn't be part of the logging instead, so it would also apply to logging e.g. URLs with encoded credentials. But I have to admit I don't see a simple way to implement that.

2022-09-27 11:41 UTC, mnonnenmacher commented
> I'm wondering whether that masking feature shouldn't be part of the logging instead, so it would also apply to logging e.g. URLs with encoded credentials. But I have to admit I don't see a simple way to implement that.

Hoplite uses a special [`Masked`](https://github.com/sksamuel/hoplite#masked-values) type for that, maybe we could implement a similar mechanism. It's basically just a [wrapper around `String`](https://github.com/sksamuel/hoplite/blob/4ed1f3397c13b12e31bc48ac06d0e9b40e9dcd37/hoplite-core/src/main/kotlin/com/sksamuel/hoplite/types.kt) that ensures that `toString()` does not print the actual value.

@oheger-bosch Would this be a feasible approach here? I think the difficulty is what type `vararg command` should have then, but the current mechanism to provide the argument index seems to be a bit fragile.

2022-09-27 13:02 UTC, oheger-bosch commented
> Hoplite uses a special [`Masked`](https://github.com/sksamuel/hoplite#masked-values) type for that, maybe we could implement a similar mechanism. It's basically just a [wrapper around `String`](https://github.com/sksamuel/hoplite/blob/4ed1f3397c13b12e31bc48ac06d0e9b40e9dcd37/hoplite-core/src/main/kotlin/com/sksamuel/hoplite/types.kt) that ensures that `toString()` does not print the actual value.
> 
> @oheger-bosch Would this be a feasible approach here? I think the difficulty is what type `vararg command` should have then, but the current mechanism to provide the argument index seems to be a bit fragile.

Agreed to the fragility argument. Could the wrapper type implement `CharSequence`, maybe using Kotlin's `by` delegate mechanism?

2022-09-27 15:51 UTC, mnonnenmacher commented
> Agreed to the fragility argument. Could the wrapper type implement `CharSequence`, maybe using Kotlin's `by` delegate mechanism?

This might be a good idea, something like this could work:

```kotlin
class Masked(val value: String) : CharSequence by MASK {
    companion object {
        private const val MASK = "***"
    }

    override fun toString(): String = MASK
}
```

This would ensure that by default all `toString()` calls get the mask but you can check for the type to get the actual value.

2022-09-29 09:45 UTC, mnonnenmacher requested changes

2022-09-29 09:45 UTC, mnonnenmacher commented on utils/common/src/main/kotlin/MaskedString.kt
> +package org.ossreviewtoolkit.utils.common
Nit: Please add an empty line between license and package.

2022-09-29 09:45 UTC, mnonnenmacher commented on utils/common/src/test/kotlin/MaskedStringTest.kt
> +package org.ossreviewtoolkit.utils.common
Nit: Please add an empty line between license and package.

2022-09-29 09:45 UTC, mnonnenmacher commented on utils/common/src/main/kotlin/MaskedString.kt
> +    }
Could be shorter: `override fun toString() = mask`

2022-09-29 09:45 UTC, mnonnenmacher commented on utils/common/src/main/kotlin/MaskedString.kt
> +    val value: CharSequence,
I think this commit is supposed to be squashed into the previous commit.

2022-09-29 10:22 UTC, mnonnenmacher approved these changes

2022-09-29 11:39 UTC, merged