Eliminate repetition in the construction of `AnalyzerRun`s
oss-review-toolkit/ort pull request #5919
Opened 2022-10-07 10:56 UTC by fviernau

A non-function refactoring which first eliminates some obsolete constants for default values and
then makes use of `AnalyzerRun.EMPY.copy()` to eliminate quite a bit of repetition.

2022-10-07 12:36 UTC, sschuberth requested changes

2022-10-07 12:36 UTC, sschuberth commented on model/src/test/kotlin/config/ExcludesTest.kt
> +                config = AnalyzerConfiguration(),
There is one more place in `RequirementsCommand`, mind simplifying that too as part of this commit?

2022-10-07 12:36 UTC, sschuberth commented on reporter/src/funTest/kotlin/reporters/spdx/SpdxDocumentReporterFunTest.kt
> +        config = AnalyzerConfiguration(),
Mind squashing this to the previous commit? I believe it's easier to review the same change in a single blow, and it avoids you to retype the same commit message.

2022-10-07 12:36 UTC, sschuberth commented on model/src/test/kotlin/licenses/TestData.kt
> +        config = AnalyzerConfiguration(),
Same here, I'd prefer a squash.

2022-10-07 12:36 UTC, sschuberth commented on advisor/src/test/kotlin/AdvisorTest.kt
> +        analyzer = AnalyzerRun.EMPTY.copy(
Nice changes!

2022-10-07 12:36 UTC, sschuberth commented on model/src/main/kotlin/AnalyzerRun.kt
> +    val endTime: Instant,
The comment above should also be changed here.

2022-10-07 16:07 UTC, sschuberth submitted a review, later dismissed

2022-10-07 16:09 UTC, sschuberth commented
Unfortunately, there's a test failure in "AnalyzerRun without timestamps can be deserialized".

2022-10-07 17:20 UTC, fviernau commented
> Unfortunately, there's a test failure in "AnalyzerRun without timestamps can be deserialized".

I've dropped the test. Hope the other tests pass now.

2022-10-07 18:35 UTC, sschuberth commented
> I've dropped the test. Hope the other tests pass now.

Yes, but now there are a few unused imports.

2022-10-09 19:19 UTC, sschuberth approved these changes

2022-10-09 19:19 UTC, merged