declared-license-mapping: Add mapping for GPL-3.0-only
oss-review-toolkit/ort pull request #6138
Opened 2022-11-29 12:56 UTC by MarcelBochtler

Found in [1].

[1]: https://repo1.maven.org/maven2/org/tmatesoft/sqljet/sqljet/1.1.15/sqljet-1.1.15.pom

2022-11-29 16:22 UTC, tsteenbe requested changes
Please add to the commit message the location where you found this license string see for example

- https://github.com/oss-review-toolkit/ort/commit/f09298675ec671e751c2aad4a5ac2869fa01bb70
-  https://github.com/oss-review-toolkit/ort/commit/0d6780d3f550859e5af1473da06f54ae339456c6
- https://github.com/oss-review-toolkit/ort/commit/965b615fe76d1792802009ab17a5520b95648778

2022-11-30 07:51 UTC, MarcelBochtler commented
> Please add to the commit message body the location where you found this license string see for example
> 
>     * [f092986](https://github.com/oss-review-toolkit/ort/commit/f09298675ec671e751c2aad4a5ac2869fa01bb70)
> 
>     * [0d6780d](https://github.com/oss-review-toolkit/ort/commit/0d6780d3f550859e5af1473da06f54ae339456c6)
> 
>     * [965b615](https://github.com/oss-review-toolkit/ort/commit/965b615fe76d1792802009ab17a5520b95648778)

There already is an example location in the commit body?!

2022-11-30 20:07 UTC, tsteenbe approved these changes

2022-11-30 20:07 UTC, merged

2022-11-30 20:08 UTC, tsteenbe commented
@MarcelBochtler  Sorry had to click a bit deeper into the GitHub UI, we are all good.