Do not use sorted sets for authors and delcared licenses
oss-review-toolkit/ort pull request #6293
Opened 2023-01-02 13:58 UTC by sschuberth

Please have a look at the individual commit messages for the details.

2023-01-02 14:07 UTC, sschuberth commented
This continues the story started in https://github.com/oss-review-toolkit/ort/pull/6244.

2023-01-03 10:25 UTC, mnonnenmacher requested changes

2023-01-03 10:25 UTC, mnonnenmacher commented on analyzer/src/main/kotlin/managers/Pub.kt
> +                    var authors = mutableSetOf<String>()
Should be `emptySet()`.

2023-01-03 10:25 UTC, mnonnenmacher commented on analyzer/src/main/kotlin/managers/Pub.kt
> +private fun parseAuthors(pubspec: JsonNode): MutableSet<String> =
Should be `Set<String>`.

2023-01-03 10:25 UTC, mnonnenmacher commented on analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt
> +    return setOf()
`emptySet()`

2023-01-03 10:25 UTC, mnonnenmacher commented on utils/ort/src/main/kotlin/DeclaredLicenseProcessor.kt
> +     * Decompose the SPDX expression or return an empty string.
`[Decompose][SpdxExpression.decompose] the [spdxExpression] or return an empty string if it is null.`

2023-01-03 11:16 UTC, mnonnenmacher approved these changes

2023-01-03 11:31 UTC, merged