Fix-up a left-over from postgres storage config properties
oss-review-toolkit/ort pull request #6315
Opened 2023-01-09 15:25 UTC by fviernau

The paths for these properties have changed by [1].

[1] https://github.com/oss-review-toolkit/ort/commit/4ea98636ff2e510bafc9fd8300433ed0cf204304

2023-01-09 15:57 UTC, mnonnenmacher requested changes

2023-01-09 15:57 UTC, mnonnenmacher commented on README.md
>    `ort__scanner__storages__postgres__schema=test_schema`.
This also needs to be fixed.

2023-01-10 08:30 UTC, mnonnenmacher approved these changes

2023-01-10 08:56 UTC, fviernau commented
Merge despite unrelated failing test.

2023-01-10 08:57 UTC, merged