Rename `OrtIssue` to `Issue`
oss-review-toolkit/ort pull request #6415
Opened 2023-01-30 11:06 UTC by fviernau

2023-01-30 14:38 UTC, mnonnenmacher requested changes

2023-01-30 14:38 UTC, mnonnenmacher commented on advisor/src/main/kotlin/advisors/GitHubDefects.kt
> +import org.ossreviewtoolkit.clients.github.issuesquery.Issue as GithubIssue
Nit: Use `GitHubIssue` for consistency.

2023-01-30 14:38 UTC, mnonnenmacher commented on advisor/src/main/kotlin/advisors/GitHubDefects.kt
> +        val githubIssues = handleError(
Nit: `gitHubIssues`

2023-01-30 14:38 UTC, mnonnenmacher commented on reporter/src/main/kotlin/reporters/evaluatedmodel/EvaluatedIssueType.kt
> +enum class EvaluatedIssueType {
Commit message: "the the" -> "with the"
Technically this is also a breaking change for programmatic use as the class is not internal.

2023-01-30 14:38 UTC, mnonnenmacher commented on reporter/src/main/kotlin/reporters/evaluatedmodel/DependencyTreeNode.kt
> +    val issues: List<EvaluatedIssue> = emptyList(),
Commit message: Technically this is also a breaking change for programmatic use as the class is not internal.

2023-01-31 08:18 UTC, MarcelBochtler commented on advisor/src/main/kotlin/advisors/GitHubDefects.kt
> +            createIssuesForReleases(pkg, gitHubIssues.applyLabelFilters(), releases, ortIssues).also {
Nit: Commit message: `releases`

2023-01-31 08:23 UTC, MarcelBochtler submitted a review, later dismissed

2023-02-01 15:03 UTC, MarcelBochtler approved these changes

2023-02-01 16:31 UTC, merged