AnalyzerCommand: Fix a file path in the log output
oss-review-toolkit/ort pull request #6435
Opened 2023-02-03 11:26 UTC by fviernau

Log the file path of the actually use repository configuration instead of the default file location.

2023-02-03 11:45 UTC, mnonnenmacher submitted a review, later dismissed

2023-02-03 15:36 UTC, mnonnenmacher requested changes

2023-02-03 15:36 UTC, mnonnenmacher commented on cli/src/main/kotlin/commands/AnalyzerCommand.kt
> +                    "Existing package curations from '${repositoryConfigurationFile.absolutePath}' are not applied " +
Commit message nit: "use**d**"

2023-02-05 11:17 UTC, sschuberth approved these changes

2023-02-05 11:17 UTC, merged