refactor(Analyzer)!: Improve package curation ordering
oss-review-toolkit/ort pull request #6451
Opened 2023-02-07 09:22 UTC by fviernau

Conistently order the package curations or the providers repsectively by higherst-priority first. This avoids confusion compared to dealing with inconsistent ordering. This way only the logic which actually applies the curations needs to reverse the curations.

Add or update the KDoc of all releated functions and properties so that the order is always specified.

2023-02-07 15:24 UTC, mnonnenmacher requested changes

2023-02-07 15:24 UTC, mnonnenmacher commented on analyzer/src/main/kotlin/Analyzer.kt
> +    /**
Commit message nit: Typos in "respectively", "highest"

2023-02-07 19:57 UTC, sschuberth commented on model/src/main/kotlin/OrtResult.kt
> + * Returns a set containing exactly one [CuratedPackage] for each given [Package], derived from applying all
"Return" (without "s").

2023-02-08 07:34 UTC, sschuberth commented
> There is no backwards compatibility for de-serializing ORT files prior to this change. Deserialization is possible, but leads to reversing the curation order.

So, doesn't this mean that the comment / order in `reference.yml` also needs to be adjust as part of this PR?

https://github.com/oss-review-toolkit/ort/blob/0a27a3813c88014572190808c341a23424fd566a/model/src/main/resources/reference.yml#L39-L68

2023-02-08 07:34 UTC, mnonnenmacher approved these changes

2023-02-08 07:39 UTC, fviernau commented
> So, doesn't this mean that the comment / order in `reference.yml` also needs to be adjust as part of this PR?

No, this change affects only the order of the list of String inside `OrtResult` (besides Kotlin code).

2023-02-08 08:13 UTC, merged

2023-02-08 08:55 UTC, sschuberth commented
> entries are ordered in highest-priority-first, which hasn't been changed. There is also no plan to change it, as the idea of this PR was to use this order everywhere.

Ok, great, I just wanted to double-check; I probably was mislead and somehow though it was exactly the opposite.