Gracefully handle package curations when replacing repository configurations
oss-review-toolkit/ort pull request #6511
Opened 2023-02-17 14:37 UTC by fviernau

See individual commits.

2023-02-17 14:41 UTC, sschuberth commented on model/src/main/kotlin/OrtResult.kt
> +import org.ossreviewtoolkit.model.ResolvedPackageCurations.Companion.REPOSITORY_CONFIGURATION_PROVIDER_ID
Commit message: s/flat/flag/

2023-02-20 17:07 UTC, mnonnenmacher requested changes

2023-02-20 17:07 UTC, mnonnenmacher commented on model/src/main/kotlin/OrtResult.kt
> +    fun replaceConfig(config: RepositoryConfiguration): OrtResult =
Please also update the documentation of the function to explain how curations contained in `config` are handled.

2023-02-21 13:34 UTC, mnonnenmacher approved these changes

2023-02-21 13:34 UTC, merged