Minor NodeJS fixes on Docker
oss-review-toolkit/ort pull request #6587
Opened 2023-03-01 14:15 UTC by heliocastro

2023-03-01 14:25 UTC, sschuberth requested changes

2023-03-01 14:25 UTC, sschuberth commented on Dockerfile
> +ARG NODEJS_VERSION=18.14.2
Commit message: Typo in "dockedr".

2023-03-02 09:07 UTC, heliocastro commented on Dockerfile
> +ARG NODEJS_VERSION=18.14.2
Fixed

2023-03-02 10:13 UTC, sschuberth approved these changes

2023-03-02 10:59 UTC, merged