Clean up Copyright statements
oss-review-toolkit/ort pull request #6837
Opened 2023-04-12 12:46 UTC by sschuberth

Please have a look at the individual commit messages for the details.

2023-04-13 07:29 UTC, tsteenbe requested changes
We can not touch the copyrights statements of third parties as their licenses require us to reproduce their exact copyright statement - ORT project itself has similar requirement in its Apache-2.0 license - https://github.com/oss-review-toolkit/ort/blob/main/LICENSE#L100-L104.

2023-04-13 07:39 UTC, tsteenbe commented on .reuse/dep5
> -Files: integrations/tekton/*
The Google attribution is already in the NOTICE file but this is the machine readable version so I would not remove it.

2023-04-13 07:40 UTC, sschuberth commented
> We can not touch the copyrights statements of third parties as their licenses require us to reproduce their exact copyright statement

Which means we need to e.g. [update these lines](https://github.com/oss-review-toolkit/ort/pull/6837/commits/4c59787d88bf39c95a72fe48c9d3ddb2ba3257fd#diff-1c645862be9de205dccc305cde10248abfe5b5a2297fc0502cbdd22cae5c9305R97-R99) whenever the Gradle wrapper changes (in a new year), right?

2023-04-13 07:42 UTC, sschuberth commented
I've dropped the last two commits.

2023-04-14 15:15 UTC, sschuberth commented
> I've dropped the last two commits.

@tsteenbe please have another look.

2023-04-18 06:08 UTC, sschuberth commented
> > I've dropped the last two commits.
> 
> @tsteenbe please have another look.

Ping once more @tsteenbe.

2023-04-20 08:22 UTC, tsteenbe approved these changes

2023-04-20 08:47 UTC, sschuberth commented
Merging despite the unrelated `ConanFunTest` failure.

2023-04-20 08:47 UTC, merged