build(analyzer): Move all Node package managers to an own plugin project
oss-review-toolkit/ort pull request #6910
Opened 2023-04-24 10:35 UTC by sschuberth

2023-04-25 15:26 UTC, mnonnenmacher requested changes

2023-04-25 15:26 UTC, mnonnenmacher commented on plugins/package-managers/build.gradle.kts
> +    api(project(":plugins:package-managers:node-package-manager"))
Commit message: Can you explain the reason why these package managers are moved into the same plugin and not into separate plugins?

2023-04-26 06:26 UTC, mnonnenmacher approved these changes

2023-04-26 06:48 UTC, sschuberth commented
Merging despite the unrelated `PipFunTest` failure.

2023-04-26 06:48 UTC, merged