Update ADOPTERS.md
oss-review-toolkit/ort pull request #6924
Opened 2023-04-25 19:09 UTC by porsche-rishisaxena

Please ensure that your pull request adheres to our [contribution guidelines](https://github.com/oss-review-toolkit/.github/blob/main/CONTRIBUTING.md). Thank you!

2023-04-25 19:31 UTC, sschuberth requested changes

2023-04-25 19:31 UTC, sschuberth commented on ADOPTERS.md
> +| [HERE Technologies](https://here.com/) | opensource@here.com | HERE Technologies uses ORT to generate SBOMs for all its products, as well as to manage licensing risks. | [Porsche AG](https://www.po
Please start a new line with

    | [Porsche AG](https://www.porsche.com/)

to fix the formatting.

2023-04-25 19:31 UTC, sschuberth commented on ADOPTERS.md
> +| [HERE Technologies](https://here.com/) | opensource@here.com | HERE Technologies uses ORT to generate SBOMs for all its products, as well as to manage licensing risks. | [Porsche AG](https://www.po
Please just say "ORT" instead of "oss review toolkit (ort)" as readers probably know the acronym.

2023-04-25 19:31 UTC, sschuberth commented on ADOPTERS.md
> +| [HERE Technologies](https://here.com/) | opensource@here.com | HERE Technologies uses ORT to generate SBOMs for all its products, as well as to manage licensing risks. | [Porsche AG](https://www.po
Hashtags like "#FOSS" are not interpreted here, so just say "FOSS".

2023-04-25 19:31 UTC, sschuberth commented on ADOPTERS.md
> +| [HERE Technologies](https://here.com/) | opensource@here.com | HERE Technologies uses ORT to generate SBOMs for all its products, as well as to manage licensing risks. | [Porsche AG](https://www.po
While true, I'd recommend to just drop the "We are active participants in the ORT community to understand, learn and collaborate on the roadmap defined within the community." sentence as this is more about how you're adopting ORT as a tool, and it makes the text a bit shorter.

2023-04-25 19:33 UTC, sschuberth commented
Also the commit message needs to be amended to adhere to conventional commits. I'd recommend

   docs(ADOPTERS): Add Porsche AG as an adopter of ORT

2023-04-26 08:10 UTC, sschuberth requested changes
There are still some minor formatting issues, and the two commits should be squash into one. @porsche-rishisaxena, if you want I can take over the PR and get this done for you.

2023-04-26 08:10 UTC, sschuberth commented on ADOPTERS.md
> +|
This pipe symbol needs to stay at the end of line 10.

2023-04-26 08:10 UTC, sschuberth commented on ADOPTERS.md
> +|
This pipe symbol needs to be put at the end of line 12 (separated with a single space from the `.` at the end of the preceding sentence, like it was originally in line 10).

2023-04-26 08:22 UTC, porsche-rishisaxena commented
> There are still some minor formatting issues, and the two commits should be squash into one. @porsche-rishisaxena, if you want I can take over the PR and get this done for you.

Hi @sschuberth. Yes sure please feel free to adjust by taking over this PR. Thank you so much.

2023-04-26 08:58 UTC, sschuberth commented
Superseded by https://github.com/oss-review-toolkit/ort/pull/6926.

2023-04-26 08:58 UTC, closed without merging