Project: Do not use a sorted set for `scopeDependencies`
oss-review-toolkit/ort pull request #7003
Opened 2023-05-16 12:12 UTC by fviernau

See individual commits.

Part of #6235.

2023-05-17 16:58 UTC, sschuberth requested changes

2023-05-17 16:58 UTC, sschuberth commented on analyzer/src/main/kotlin/managers/GoDep.kt
> +                    scopeDependencies = mutableSetOf(scope)
Commit message:
- Probably put `scopeDependencies` into backticks (as you do so for `scopeNames` in the next commit)
- Typo in "unk*n*own"

2023-05-17 16:58 UTC, sschuberth commented on model/src/main/kotlin/utils/DependencyGraphBuilder.kt
> +    fun scopesFor(prefix: String, unqualify: Boolean = true): Set<String> {
Commit message: Typo in "prece~e~ding" (the stroked through "e" does not really render well)

2023-05-18 06:13 UTC, fviernau commented on analyzer/src/main/kotlin/managers/GoDep.kt
> +                    scopeDependencies = mutableSetOf(scope)
The backticks don't fit into the 72 chars.

2023-05-18 09:24 UTC, sschuberth commented on analyzer/src/main/kotlin/managers/GoDep.kt
> +                    scopeDependencies = mutableSetOf(scope)
> The backticks don't fit into the 72 chars.

IIRC we've configured commitlint to allow 75 chars in the title like in the body (even if GitHub itself suggests 72 chars).

2023-05-22 06:41 UTC, sschuberth approved these changes

2023-05-22 07:00 UTC, merged