Start mitraging scanner plugins to separate projects
oss-review-toolkit/ort pull request #7167
Opened 2023-06-21 08:32 UTC by sschuberth

Please have a look at the individual commit messages for the details.

2023-06-21 11:48 UTC, fviernau commented on settings.gradle.kts
> +    include(":$it")
It wasn't super obvious to me what these two `it`s in line 65 and 67 refer to.
How about fixing this by using some variable, like e.g:

```
val moduleNames = file("plugins").walk().maxDepth(3).filter {
    it.isFile && it.name == "build.gradle.kts"
}.mapTo(mutableListOf()) {
    ":${it.parentFile.toRelativeString(rootDir).replace(File.separatorChar, ':')}" 
}

moduleNames.forEach { moduleName ->
     include(moduleName)
     ...
}
```

2023-06-21 11:48 UTC, fviernau commented on settings.gradle.kts
> +    }
To me it's hard to grasp what

1. The condition in line 71 is about. Would it make sense to replace it with a hard coded ignore list for
     readability?
2. The reason why the "s" is stripped from the name in line 72

In general, would it make sense to add some code comment before line 62 (stating the purpose of the below code block) and to the logic in the function, to explain a bit the what and why / idea?

2023-06-21 11:48 UTC, fviernau commented on plugins/commands/scanner/build.gradle.kts
> +    implementation(platform(project(":plugins:scanners")))
commit-msg: "This changes requires" -> "This change requires"?

2023-06-21 13:39 UTC, fviernau commented
LGTM now ok from my side. Maybe we can have one more reviewer? @oss-review-toolkit/core-devs ?

2023-06-22 10:46 UTC, mnonnenmacher requested changes

2023-06-22 10:46 UTC, mnonnenmacher commented on settings.gradle.kts
> +        }
I think a when expression would look nicer here:
```kotlin
        project(":$projectPath").name = when(parts[2]) {
            "api" -> "$singularTypeName-api"
            else -> "${parts[2]}-$singularTypeName"
        }
```

2023-06-22 13:07 UTC, mnonnenmacher approved these changes

2023-06-22 13:07 UTC, merged