Advisor details improvements
oss-review-toolkit/ort pull request #7199
Opened 2023-06-25 19:26 UTC by sschuberth

Please have a look at the individual commit messages for the details.

2023-06-25 20:45 UTC, mnonnenmacher requested changes

2023-06-25 20:45 UTC, mnonnenmacher commented on evaluator/src/test/kotlin/TestData.kt
> +                        advisor = AdvisorDetails("Advisor"),
Commit message nit "an**y**way"

2023-06-26 06:52 UTC, mnonnenmacher approved these changes

2023-06-26 07:47 UTC, sschuberth commented
Merging despite the unrelated `YarnFunTest` failure.

2023-06-26 07:48 UTC, merged