SpdxDocumentReporter: Include file information for dependencies
oss-review-toolkit/ort pull request #7255
Opened 2023-07-07 08:17 UTC by fviernau

Extend the SPDX document reporter to include file information for
dependencies for all files which have at least one license or copyright
finding. Make the file information include the detected licenses,
copyright statements as well as the mandatory sha1 checksums.

Also an option to disable this feature, as it may not always be desired to include file information.

Fixes #6947.

2023-07-07 10:10 UTC, sschuberth commented
This will get rebased onto https://github.com/oss-review-toolkit/ort/pull/7246, right?

2023-07-07 10:12 UTC, fviernau commented
> This will get rebased onto #7246, right?

Yes.

2023-07-10 20:59 UTC, mnonnenmacher requested changes

2023-07-10 20:59 UTC, mnonnenmacher commented on plugins/reporters/spdx/src/main/kotlin/Extensions.kt
> +private data class FileFindings(
Please add short docs for the class.

2023-07-10 20:59 UTC, mnonnenmacher commented on plugins/reporters/spdx/src/main/kotlin/Extensions.kt
> +            // The sha1 is not available in case path is not withing the VCS path.
Nit: "the path", "within~~g~~"

2023-07-10 20:59 UTC, mnonnenmacher commented on plugins/reporters/spdx/src/main/kotlin/Extensions.kt
> + * [sourceCodeOrigin] associated with the copyright findings under the respective path, or `null` if the
Better say "copyright statements" here as the result contains only the statements.

2023-07-10 20:59 UTC, mnonnenmacher commented on plugins/reporters/spdx/src/main/kotlin/Extensions.kt
> +        .flatten()
Use `flatMap`.

2023-07-10 20:59 UTC, mnonnenmacher commented on plugins/reporters/spdx/src/main/kotlin/SpdxDocumentReporter.kt
> +        const val OPTION_FILE_INFORMATION_ENABLED = "file.information.enabled"
Option needs to be explained in the class docs.

2023-07-11 06:42 UTC, fviernau commented on plugins/reporters/spdx/src/main/kotlin/Extensions.kt
> + * returned file, and it's respective value is used as a part of the generated SPDX ID of the files.
> I'm not familiar with SPDX documents, if this is not done already elsewhere, can you add a link to the SPDX specs explaining what file IDs are?

[SpdxFile] is a link, so you can click on it. Once you navigate to the IDs to learn about them, you'll find I've updated that comment to link to [SpdxDocument] which contains the links to the specs and examples.

2023-07-11 10:40 UTC, mnonnenmacher approved these changes

2023-07-11 16:06 UTC, fviernau commented
The failing test, `NuGetFunTest`, is unrelated. Merge regardlessly.

2023-07-11 16:06 UTC, merged