React over documentation
oss-review-toolkit/ort pull request #7525
Opened 2023-09-18 12:01 UTC by heliocastro

For documentation change only, build-and-test pipeline can be ignored. For docusaurus-test, it only needed if effective changes happened in the docusaurus folder.

2023-09-18 12:44 UTC, mnonnenmacher requested changes

2023-09-18 13:01 UTC, heliocastro commented on .github/workflows/docusaurus-test.yml
> +      - docusaurus/**
@mnonnenmacher Done

2023-09-19 14:44 UTC, mnonnenmacher commented on .github/workflows/build-and-test.yml
> +      - docussaurus/**
Unfortunately this turns out to be a real issue. As you can see in this PR, the "Docusaurus Test" is skipped, but as it is a required check this blocks the PR from getting merged. Also it seems there is no good solution for this, see:
https://github.com/github/docs/issues/8926
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks

It seems the only workaround is to use a conditional instead:
https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution
However, I don't know how tricky it is to make a conditional that checks if certain paths have been changed in the PR.

@sschuberth Are you maybe aware of any solution for that issue?

2023-09-19 15:43 UTC, sschuberth commented on .github/workflows/build-and-test.yml
> +      - docussaurus/**
> Are you maybe aware of any solution for that issue?

No. Conditionals seem to be the only way out.

2024-02-08 17:17 UTC, closed without merging