Log4j simplifications
oss-review-toolkit/ort pull request #7651
Opened 2023-10-06 17:18 UTC by sschuberth

Please have a look at the individual commit messages for the details.

2023-10-07 09:19 UTC, mnonnenmacher requested changes

2023-10-07 09:19 UTC, mnonnenmacher commented on utils/ort/src/main/kotlin/OkHttpClientHelper.kt
> +/**
Commit message: "frist" -> "first"

2023-10-07 11:35 UTC, mnonnenmacher approved these changes

2023-10-07 12:12 UTC, merged

2023-10-16 08:34 UTC, nnobelis commented
IMO this is a breaking change: since `Logging` was public API before, external plugins could have used it.

2023-10-16 08:52 UTC, sschuberth commented
> IMO this is a breaking change: since `Logging` was public API before, external plugins could have used it.

Yes, right. For the PRs / version bumping it's too late, but I'll at least label this PR accordingly.

2023-10-16 09:02 UTC, nnobelis commented
@sschuberth: Before this PR, the loggers were throwing exception if the calling classes were not in `org.ossreviewtoolkit.`.
Therefore, the plugins used to piggyback on an ORT class logger to output their messages.

Now, they cannot use ORT classes' loggers but it should not be a problem since the aforementioned exception is not thrown anymore. Right ?

2023-10-16 09:36 UTC, sschuberth commented
> Before this PR, the loggers were throwing exception if the calling classes were not in `org.ossreviewtoolkit.`.

I don't believe that's true. That code was already removed way back in 606da3a305738e6bb68314f88b4eb7bd3ca84040.

However, I acknowledge that this PR reintroduces a behavior that 606da3a305738e6bb68314f88b4eb7bd3ca84040 circumvented, which is to "Stop polluting `Any` object with a `logger` property". This "pollution" is now back again (for files that import the extension property), but by now I actually regard this to be less of an issue, as also with the previous code logging on the wrong class could haven happened by accidentally using the base class's logger in derived classes.

> since the aforementioned exception is not thrown anymore. Right ?

The exception is not thrown in any case anymore.

2023-10-16 09:52 UTC, nnobelis commented
Understood thanks !