docs(README): Fix links to configuration file docs
oss-review-toolkit/ort pull request #7700
Opened 2023-10-15 09:22 UTC by fviernau

2023-10-15 17:32 UTC, sschuberth requested changes

2023-10-15 17:32 UTC, sschuberth commented on README.md
> +* *Notifier* - sends result notifications via different channels (like [emails](./examples/example.notifications.kts)
Commit message:

> The notifier is not a separate tool

Actually it is, both as a CLI command and as a Gradle module, so the commit message should be corrected in this regard.

2023-10-16 11:20 UTC, sschuberth commented
Please also rebase to skip the first commit, which should be equal to @nnobelis's change.

2023-11-08 15:17 UTC, fviernau commented on README.md
> +* [*Analyzer*](./website/docs/tools/analyzer.md) - determines the dependencies of projects and their metadata,
Shall I close this PR then ?

2023-11-09 21:43 UTC, sschuberth commented on README.md
> +* [*Analyzer*](./website/docs/tools/analyzer.md) - determines the dependencies of projects and their metadata,
I don't think we should close this completely, as there are some valid changes in here that would fix the link check errors I'm running into e.g. [here](https://github.com/oss-review-toolkit/ort/actions/runs/6817585531/job/18541391376#step:4:42).

So basically, I believe we should drop the changes in *this* hunk, but keep the 3 link fixes below.

2023-11-10 10:32 UTC, sschuberth approved these changes

2023-11-10 12:47 UTC, sschuberth approved these changes

2023-11-10 12:47 UTC, sschuberth commented on README.md
> +URLs and using the [appropriate VCS tool](./plugins/version-control-systems) to check out source code from version
Thanks!

2023-11-13 07:34 UTC, merged

2023-11-13 07:35 UTC, fviernau commented
Failing tests we're all unrelated.