(config) Add forceOverwrite option in ort configuration reference.yml file
oss-review-toolkit/ort pull request #8003
Opened 2023-12-06 18:53 UTC by dineshr93

Added option to overwrite existing result files if already exists in ort configuration reference.yml

2023-12-19 16:13 UTC, mnonnenmacher requested changes

2023-12-19 16:13 UTC, mnonnenmacher commented on model/src/main/resources/reference.yml
> +  forceOverwrite: true
@dineshr93 Thank you for the contribution. Please put these lines in alphabetical order (so before `licenseFilePatterns`) and surround it with single empty lines for a better overview. And please also add this line at the same location to the `OrtConfigurationTest.kt` which verifies that the reference.yml is correctly parsed:
`ortConfig.forceOverwrite shouldBe true`

To pass the functional tests you will have to rebase your branch.
To pass the commitlint check you need to change the title to e.g.:
"feat(config): Add forceOverwrite option to reference.yml"

Also, please start the sentence in the commit message body capitalized and end it with a dot, but actually you could just remove it as to me the title is self contained.

2023-12-19 16:13 UTC, mnonnenmacher commented on model/src/main/resources/reference.yml
> +  # To overwrite if the reports (analyzer-result.yml) already exists
Just use the same wording as for the configuration property in `OrtConfiguration.kt`:
"Force overwriting of any existing output files."

2023-12-19 18:04 UTC, sschuberth commented
@dineshr93 there's now a merge commit in your PR, which is something that we do not allow. Please rebase instead of merge in order to catch up your PR with upstream changes.

2024-01-08 20:47 UTC, sschuberth commented
@dineshr93 are you planning to continue the work on this PR?

2024-01-21 08:16 UTC, dineshr93 commented
Hi @sschuberth  Please take this pull request https://github.com/oss-review-toolkit/ort/pull/8146  instead of this pull request Thanks

2024-01-21 13:13 UTC, sschuberth commented
> Please take this pull request #8146 instead of this pull request

Thanks. However, organizational-wise it would have been easier for us to continue in this PR with rewritten Git history. Please keep that in mind for future contributions.

2024-01-21 13:13 UTC, closed without merging

2024-01-21 15:36 UTC, dineshr93 commented
> > Please take this pull request #8146 instead of this pull request
> 
> Thanks. However, organizational-wise it would have been easier for us to continue in this PR with rewritten Git history. Please keep that in mind for future contributions.

I am not sure how to remove the merge commit Thats why.. However What would be the steps to remove the merge commit and do debasing while already raised a pull request?

2024-01-21 16:55 UTC, sschuberth commented
> What would be the steps to remove the merge commit and do debasing while already raised a pull request?

Just reset our local branch to the commit before the merge commit(s), then rebase the branch onto latest `origin/main` (fetch first), and force-push your branch.