feat(jenkins): Allow to specifc an input path within the repository
oss-review-toolkit/ort pull request #8263
Opened 2024-02-12 17:17 UTC by sschuberth

This can be useful when enabling only a single package manager and pointing the analyzer to a single file for testing analysis of a single project.

2024-02-12 21:19 UTC, mnonnenmacher requested changes

2024-02-12 21:19 UTC, mnonnenmacher commented on integrations/jenkins/Jenkinsfile
> +            description: 'The path to analyze, relative to the repository root.',
You could add here that it is possible to set the path to a definition file to analyze only that single project.

2024-02-13 07:44 UTC, fviernau approved these changes

2024-02-13 08:15 UTC, mnonnenmacher approved these changes

2024-02-13 08:15 UTC, merged