fix(go): Disable the GOPATH mode to fix the fun tests
oss-review-toolkit/ort pull request #8324
Opened 2024-02-21 14:44 UTC by fviernau

Recently, the fun tests for `GoDep` started failing which was roughly the same time as the major version upgrade to 1.22.0 in ORT's docker images. As the GOPATH mode will eventually be remoed ^[1], just disable it now to fix the tests. In particular, do so even though the root cause of the failing tests is unkown, as `GoDep` is rather outdated and thus cannot satisfy putting in further efforts.

[1]: https://github.com/golang/go/issues/41330#issuecomment-690807092

2024-02-21 14:54 UTC, sschuberth requested changes

2024-02-21 15:00 UTC, sschuberth commented on plugins/package-managers/go/src/main/kotlin/GoDep.kt
> +        environment = mapOf("GOPATH" to gopath.path)
"docker" as a proper noun is still lowercase, but unfortunately the change does not seem to fix the `GoDepFunTest` anyway 😢

2024-02-21 15:22 UTC, fviernau commented on plugins/package-managers/go/src/main/kotlin/GoDep.kt
> +        environment = mapOf("GOPATH" to gopath.path)
As I don't have the time let's try this for now: https://github.com/oss-review-toolkit/ort/pull/8325

2024-02-22 07:42 UTC, closed without merging

2024-02-22 07:42 UTC, fviernau commented
Temporarily fix by reverting the Go major version upgrade. This approach in this PR didn't work out.