Allow to set the `sourceCodeOrigins` priority on package granularity
oss-review-toolkit/ort pull request #8406
Opened 2024-03-12 14:12 UTC by fviernau

If one wants to scan a certain package with a different source code origin priority, the only work around to make ORT do so was to nullify the "other" provenance. This PR introduces a dedicated, machine readable property which allows to write clean fixes in this use case which in turn is enables such curations, e.g. potentially in 'ort-config'.

Fixes #8402.

2024-03-13 14:03 UTC, mnonnenmacher requested changes

2024-03-13 14:03 UTC, mnonnenmacher commented on scanner/src/main/kotlin/provenance/PackageProvenanceResolver.kt
Commit message: Please provide a bit more detail in the body.

2024-03-13 14:03 UTC, mnonnenmacher commented on scanner/src/test/kotlin/ScannerTest.kt
> +    override fun resolveProvenance(
There should also be some new test in this file to verify that the feature works as intended.

2024-03-14 14:16 UTC, fviernau commented on scanner/src/main/kotlin/provenance/PackageProvenanceResolver.kt
> +    fun resolveProvenance(pkg: Package, defaultSourceCodeOriginsPriority: List<SourceCodeOrigin>): KnownProvenance
Fine if I make a separate commit to drop the priority?

2024-03-14 14:20 UTC, sschuberth commented on scanner/src/main/kotlin/provenance/PackageProvenanceResolver.kt
> +    fun resolveProvenance(pkg: Package, defaultSourceCodeOriginsPriority: List<SourceCodeOrigin>): KnownProvenance
It's fine with me, but I guess we should get agreement from @mnonnenmacher as I seem to remember that he liked the "Priority" suffix.

2024-03-14 15:50 UTC, mnonnenmacher commented on scanner/src/main/kotlin/provenance/PackageProvenanceResolver.kt
> +    fun resolveProvenance(pkg: Package, defaultSourceCodeOriginsPriority: List<SourceCodeOrigin>): KnownProvenance
I'm fine with the renaming but please then also append "...in order of priority" to the first sentence of the function docs.

2024-03-14 15:50 UTC, mnonnenmacher commented on scanner/src/main/kotlin/provenance/PackageProvenanceResolver.kt
> +    fun resolveProvenance(pkg: Package, defaultSourceCodeOriginsPriority: List<SourceCodeOrigin>): KnownProvenance
@fviernau Are you going to add the commit here? Then I'll wait with the approval.

2024-03-14 21:37 UTC, fviernau commented on scanner/src/main/kotlin/provenance/PackageProvenanceResolver.kt
> +    fun resolveProvenance(pkg: Package, defaultSourceCodeOriginsPriority: List<SourceCodeOrigin>): KnownProvenance
@mnonnenmacher I'll make a follow up PR, so this can move forward.

2024-03-15 09:22 UTC, sschuberth approved these changes

2024-03-15 09:24 UTC, merged

2024-03-15 10:37 UTC, fviernau commented on scanner/src/main/kotlin/provenance/PackageProvenanceResolver.kt
> +    fun resolveProvenance(pkg: Package, defaultSourceCodeOriginsPriority: List<SourceCodeOrigin>): KnownProvenance
Here it is: https://github.com/oss-review-toolkit/ort/pull/8426.