Upgrade ScanCode to version 32.1.0
oss-review-toolkit/ort pull request #8470
Opened 2024-03-28 15:46 UTC by sschuberth

Please have a look at the individual commit messages for the details.

2024-04-02 14:01 UTC, mnonnenmacher requested changes

2024-04-02 14:01 UTC, mnonnenmacher commented on plugins/scanners/scancode/src/main/kotlin/ScanCodeResultModel.kt
Commit message: Could you explain the change a bit more detailed? IIUC license findings that are references to license findings in other files are now ignored, because they already appear as findings for those other files?

2024-04-02 14:45 UTC, sschuberth commented on plugins/scanners/scancode/src/main/kotlin/ScanCodeResultModel.kt
Exactly. I've used your wording for the commit message.

2024-04-02 14:46 UTC, fviernau commented on plugins/scanners/scancode/src/main/kotlin/ScanCodeResultModel.kt
I've added another comment to the ScanCode issue, it could be considered here (and in the commit message) as well: https://github.com/nexB/scancode-toolkit/issues/3648#issuecomment-2032239964

2024-04-02 15:06 UTC, mnonnenmacher approved these changes

2024-04-02 15:11 UTC, merged

2024-04-02 15:31 UTC, fviernau commented on plugins/scanners/scancode/src/main/kotlin/ScanCodeResultModel.kt
> Note that keeping findings that are in fact references is not currently supported by the ORT data model. That's because line ranges always have to refer to the file from the finding, not a references file. 

This indicates to me that you likely didn't get my point. Consider this:

1. In older ScanCode versions we had `License-scancode-unkown-license-reference` findings
    with start / endLine pointing to the scanned file.
2. In newer ScanCode version findings such as 1. do not appear, but they are replaced with the licenses 
    detected in the referenced file.

This commit now filters out the findings. So, compared to older ScanCode version scan results the `License-scancode-unkown-license-reference` findings are missing. I think this is undesired and should be avoided.

2024-04-03 06:31 UTC, sschuberth commented on plugins/scanners/scancode/src/main/kotlin/ScanCodeResultModel.kt
I've asked for clarification [over here](https://github.com/nexB/scancode-toolkit/issues/3648#issuecomment-2033662900).