deps: Update S3 to version 2.25.28
oss-review-toolkit/ort pull request #8508
Opened 2024-04-11 08:56 UTC by MarcelBochtler

This updated version updates netty-codec-http to version `4.1.108.Final` which fixed the vulnerability CVE-2024-29025 [1].
Unfortunately, no release notes are published.

[1]: https://nvd.nist.gov/vuln/detail/CVE-2024-29025

Please ensure that your pull request adheres to our [contribution guidelines](https://github.com/oss-review-toolkit/.github/blob/main/CONTRIBUTING.md). Thank you!

2024-04-11 10:05 UTC, tsteenbe requested changes
Was a bit confused when I first read this PR so believe commit message can be improved. @MarcelBochtler  What do you think of the following?

```
deps: Update S3 to version 2.25.28

This newer version uses netty-codec-http version `4.1.108.Final`
which includes a fix for the CVE-2024-29025 known vulnerability [1] .

Unfortunately, no release notes are published.

[1]: https://github.com/advisories/GHSA-5jpm-x58v-624v
```

2024-04-11 18:29 UTC, sschuberth commented
> Unfortunately, no release notes are published.

Aren't [these](https://github.com/aws/aws-sdk-java-v2/releases/tag/2.25.28) the release notes? They don't mention the netty-codec-http update, though.

2024-04-11 18:43 UTC, sschuberth commented
And actually, [this](https://github.com/aws/aws-sdk-java-v2/commit/3dcb0ec89e4a598328ed8438207e7cff1e468a31) looks like Netty was already updated back in version [2.25.19](https://github.com/aws/aws-sdk-java-v2/releases/tag/2.25.19). So if your argument is only to remedy the CVE, then updating to that version would be sufficient. At least you should not make it sound as if version 2.25.28 would be required to address the issue.

2024-04-12 06:48 UTC, MarcelBochtler commented
> > Unfortunately, no release notes are published.
> 
> Aren't [these](https://github.com/aws/aws-sdk-java-v2/releases/tag/2.25.28) the release notes? They don't mention the netty-codec-http update, though.

Thanks, I was somehow not able to find them.

> And actually, [this](https://github.com/aws/aws-sdk-java-v2/commit/3dcb0ec89e4a598328ed8438207e7cff1e468a31) looks like Netty was already updated back in version [2.25.19](https://github.com/aws/aws-sdk-java-v2/releases/tag/2.25.19). So if your argument is only to remedy the CVE, then updating to that version would be sufficient. At least you should not make it sound as if version 2.25.28 would be required to address the issue.

My reason to upgrade was the CVE.
And when upgrading I always use the latest version.

I updated the commit message, trying to clarify this.

> Was a bit confused when I first read this PR so believe commit message can be improved. @MarcelBochtler What do you think of the following?

Yes, the previous commit message was a bit confusing. I updated it.

2024-04-12 07:04 UTC, fviernau requested changes

2024-04-12 07:04 UTC, fviernau commented on gradle/libs.versions.toml
>  springCore = "5.3.33"
Unrelated change in line 59.

2024-04-12 07:55 UTC, merged