chore(docker): Update Pnpm to the latest version
oss-review-toolkit/ort pull request #8676
Opened 2024-05-22 11:53 UTC by fviernau

See also [1].

[1]: https://github.com/pnpm/pnpm/releases/tag/v9.1.2

2024-05-22 12:03 UTC, sschuberth approved these changes

2024-05-22 12:05 UTC, MarcelBochtler approved these changes

2024-05-23 07:37 UTC, sschuberth commented
Interestingly, this [adds some new packages](https://github.com/oss-review-toolkit/ort/actions/runs/9193909850/job/25288128247?pr=8676#step:7:1411).

2024-05-27 20:59 UTC, fviernau commented
@MarcelBochtler  do you recall, whether it was intended that `package-b` does not appear in the expected result of the workspaces project, but `package-a` does?

I'd like to understand why not both should be part of the result, see also 
https://github.com/oss-review-toolkit/ort/pull/5611/commits/205349609f4c71d72c2ecffff1a0c75856844153.

2024-06-07 11:34 UTC, sschuberth commented
> @MarcelBochtler do you recall, whether it was intended that `package-b` does not appear in the expected result of the workspaces project, but `package-a` does?
> 
> I'd like to understand why not both should be part of the result, see also [2053496](https://github.com/oss-review-toolkit/ort/commit/205349609f4c71d72c2ecffff1a0c75856844153).

As meanwhile [PNPM version 9.2.0 was released](https://github.com/pnpm/pnpm/releases/tag/v9.2.0) which I'm interested in, I'd have the same question to @MarcelBochtler to move this forward.

2024-06-11 14:54 UTC, MarcelBochtler commented
> @MarcelBochtler do you recall, whether it was intended that `package-b` does not appear in the expected result of the workspaces project, but `package-a` does?
> 
> I'd like to understand why not both should be part of the result, see also [2053496](https://github.com/oss-review-toolkit/ort/commit/205349609f4c71d72c2ecffff1a0c75856844153).

I don't recall it from the top of my head. I would need to investigate this. I had a quick look at the setup and for me it also looks like both packages should be part of the result.

2024-06-12 09:01 UTC, fviernau commented
I also believe it is correct to add the two new packages. I've updated the commit to cover it with a rationale.

2024-06-12 10:58 UTC, sschuberth requested changes

2024-06-12 10:58 UTC, sschuberth commented on docker/versions.dockerfile
> +ARG PNPM_VERSION=9.2.0
Commit message nit: "for unknown reason" -> "for unknown reason*s*" or "for *an* unknown reason"

2024-06-12 10:58 UTC, sschuberth commented on plugins/package-managers/node/src/funTest/assets/projects/synthetic/pnpm-workspaces/pnpm-lock.yaml
> +lockfileVersion: '9.0'
Just FYI, running `install` [with `--lockfile-only`](https://pnpm.io/cli/install#--lockfile-only) would probably have been sufficient.

2024-06-12 13:13 UTC, sschuberth approved these changes

2024-06-12 13:13 UTC, merged