chore(model): Remove the unused `createMissingArchives` scanner options
oss-review-toolkit/ort pull request #8750
Opened 2024-06-11 14:35 UTC by sschuberth

The condition that used that option was removed in c71628d, and there is no plan to reintroduce it as the current provenance-based scanner logic works differently.

2024-06-11 14:43 UTC, fviernau submitted a review, later dismissed

2024-06-11 14:43 UTC, mnonnenmacher requested changes

2024-06-11 14:43 UTC, mnonnenmacher commented on integrations/schemas/ort-configuration-schema.json
Commit message nit: "options" -> "option"

2024-06-11 14:50 UTC, mnonnenmacher approved these changes

2024-06-12 06:54 UTC, fviernau approved these changes

2024-06-12 06:54 UTC, merged