node: Port all remaining Jackson-based code to KxS
oss-review-toolkit/ort pull request #9125
Opened 2024-09-11 15:40 UTC by fviernau

See individual commits.

2024-09-11 16:05 UTC, sschuberth requested changes

2024-09-11 16:05 UTC, sschuberth commented on plugins/package-managers/node/src/main/kotlin/yarn2/Yarn2.kt
> +    }
Better use

    when (type) {
        YarnDependencyType.DEPENDENCIES -> dependencies
        YarnDependencyType.DEV_DEPENDENCIES -> devDependencies
    }

Kotlin will recognize that the `when` is exhaustive, so no `else` is needed.

2024-09-11 16:05 UTC, sschuberth commented on plugins/package-managers/node/src/main/kotlin/yarn2/Yarn2.kt
> +import org.ossreviewtoolkit.plugins.packagemanagers.node.yarn2.Yarn2.Companion.YARN2_RESOURCE_FILE
Commit message: Typo in `.yarn*r*c.yml`.

2024-09-11 16:05 UTC, sschuberth commented on plugins/package-managers/node/src/main/kotlin/yarn2/Yarn2.kt
> +    requireNotNull(yarnPath) { "No Yarn 2+ executable could be found in '$YARN2_RESOURCE_FILE'." }
While at it, maybe simplify to

    val yarnPath = yarnConfig.get<YamlScalar>(YARN_PATH_PROPERTY_NAME)?.content

    require(!yarnPath.isNullOrEmpty()) { "No Yarn 2+ executable could be found in '$YARN2_RESOURCE_FILE'." }

Again, I'm unsure whether we need to cover the pathological bank case.

2024-09-11 20:29 UTC, sschuberth submitted a review, later dismissed

2024-09-12 07:21 UTC, nnobelis approved these changes

2024-09-12 07:21 UTC, merged