feat(cli): Add a command to list installed plugins
oss-review-toolkit/ort pull request #9140
Opened 2024-09-15 13:40 UTC by mnonnenmacher

Add a command to list all installed plugins and their configuration options.

The command is limited to plugins using the new plugin API, missing plugins will be added once they are migrated.

2024-09-15 17:20 UTC, sschuberth commented
For reference, output looks like this:

```
============================ Installed ORT Plugins ============================

------------------------------ Advice Providers -------------------------------

Nexus IQ (id: NexusIQ)
An advisor that uses Sonatype's Nexus IQ Server to determine vulnerabilities in dependencies.

Configuration options:
 * serverUrl: STRING (Required)
   The URL to use for REST API requests against the server.
 * browseUrl: STRING
   A URL to use as a base for browsing vulnerability details. If not set, the [serverUrl] is used.
 * username: SECRET
   The username to use for authentication. If not both [username] and [password] are provided, authentication is
    disabled.
 * password: SECRET
   The password to use for authentication. If not both [username] and [password] are provided, authentication is
    disabled.

OSS Index (id: OSSIndex)
An advisor that uses Sonatype's OSS Index to determine vulnerabilities in dependencies.

Configuration options:
 * serverUrl: STRING (Default: https://ossindex.sonatype.org/)
   The base URL of the OSS Index REST API.
 * username: SECRET
   The username to use for authentication. If not both [username] and [password] are provided, authentication is
    disabled.
 * password: SECRET
   The password to use for authentication. If not both [username] and [password] are provided, authentication is
    disabled.

OSV
An advisor that retrieves vulnerability information from the Open Source Vulnerabilities database.

Configuration options:
 * serverUrl: STRING (Default: https://api.osv.dev)
   The base URL of the OSV REST API. If undefined, default is the production endpoint of the official OSV.dev API.

VulnerableCode
An advisor that uses a VulnerableCode instance to determine vulnerabilities in dependencies.

Configuration options:
 * serverUrl: STRING (Default: https://public.vulnerablecode.io)
   The base URL of the VulnerableCode REST API. By default, the public VulnerableCode instance is used.
 * apiKey: SECRET
   The optional API key to use.
 * readTimeout: LONG
   The read timeout for the server connection in seconds. Defaults to whatever is the HTTP client's default value.

----------------------- Package Configuration Providers -----------------------

Default Dir Package Configuration Provider (id: DefaultDir)
A package configuration provider that loads package curations from the default directory.

Dir Package Configuration Provider (id: Dir)
Provides package configurations from a directory.

Configuration options:
 * path: STRING (Required)
   The path of the package configuration directory.
 * mustExist: BOOLEAN (Default: false)
   A flag to denote whether the path is required to exist.

Double Open Server Package Configuration Provider (id: DOS)
A package configuration provider that loads package configurations from a Double Open Server instance.

Configuration options:
 * url: STRING (Required)
   The URL where the DOS backend is running.
 * token: SECRET (Required)
   The secret token to use with the DOS backend.
 * timeout: LONG
   The timeout for communicating with the DOS backend, in seconds.

ort-config (id: ORTConfig)
A package configuration provider that loads package configurations from the ort-config repository.

------------------------- Package Curation Providers --------------------------

ClearlyDefined
Provides package curation data from the ClearlyDefined service.

Configuration options:
 * serverUrl: STRING (Default: https://api.clearlydefined.io)
   The URL of the ClearlyDefined server to use.
 * minTotalLicenseScore: INTEGER (Default: 0)
   The minimum total score for a curation to be accepted. Must lie within 0 to 100.

Default Dir Package Curation Provider (id: DefaultDir)
A package curation provider that loads package curations from the default directory.

Default File Package Curation Provider (id: DefaultFile)
A package curation provider that loads package curations from the default file.

File Package Curation Provider (id: File)
A package curation provider that loads package curations from files.

Configuration options:
 * path: STRING (Required)
   The path of the package curation file or directory.
 * mustExist: BOOLEAN (Default: false)
   A flag to denote whether the path is required to exist.

ort-config (id: ORTConfig)
A package curation provider that loads package curations from the ort-config repository.

SW360 Package Curation Provider (id: SW360)
Provides package metadata from the configured SW360 instance using the REST API.

Configuration options:
 * restUrl: STRING (Required)
   The REST API URL of SW360.
 * authUrl: STRING (Required)
   The authentication URL of your SW360 instance.
 * username: SECRET (Required)
   The username for the requests to SW360.
 * password: SECRET (Default: )
   The password of the SW360 user.
 * clientId: SECRET (Required)
   The client ID of the SW360 instance for the two-step authentication.
 * clientPassword: SECRET (Default: )
   The password of the client ID.
 * token: SECRET (Default: )
   Optional access token that can be used instead of the [authUrl], [username], [password], [clientId] and
    [clientPassword] if the token is already known.
```

2024-09-15 17:25 UTC, sschuberth requested changes
We already have `ort requirements --list=plugins`. Could you please detail in the commit message what's you plan regarding the relation of these commands? I guess once all plugins are migrated, `ort requirements` should stop listed plugins at all, and the whole `--list` option to that command could be removed?

2024-09-15 17:25 UTC, sschuberth commented on plugins/commands/plugins/src/main/kotlin/PluginsCommand.kt
> +        echo(HorizontalRule("Installed ORT Plugins", "="))
Personally, I'd omit this rule as it's clear from the command that ORT plugins are listed, and instead "promote" plugin type rules from "-" to "=", and introduce "-" rules for the individual plugins to better separate their options from the next plugin.

2024-09-16 17:42 UTC, mnonnenmacher commented
> We already have `ort requirements --list=plugins`. Could you please detail in the commit message what's you plan regarding the relation of these commands? I guess once all plugins are migrated, `ort requirements` should stop listed plugins at all, and the whole `--list` option to that command could be removed?

I wasn't even aware of the `--list=plugins` option. So would you prefer to extend the output of that option or to have the separate `plugins` command?

2024-09-16 17:52 UTC, sschuberth commented
> I wasn't even aware of the `--list=plugins` option.

It's even documented 😉

https://github.com/oss-review-toolkit/ort/blob/a9e964edcdb00501ac58e1fe36b314a2bad9a30c/cli/src/main/dist/plugin/README.md?plain=1#L3

> So would you prefer to extend the output of that option or to have the separate `plugins` command?

I'm fine with having a separate command, as plugins are not really "requirements" after all (though you might *expect* a specific plugin to be present), and a dedicated sub-command could have more options to e.g. print out the plugin descriptor in JSON format. I probably just was too lazy to introduce a separate sub-command back then 😉

2024-09-16 17:55 UTC, sschuberth commented on plugins/commands/plugins/src/main/kotlin/PluginsCommand.kt
> +                    UnorderedList(
What do you think about using a [table](https://ajalt.github.io/mordant/guide/#tables) instead, with columns for the option name, type, and description?

2025-02-13 11:12 UTC, mnonnenmacher commented on plugins/commands/plugins/src/main/kotlin/PluginsCommand.kt
> +                    UnorderedList(
I gave it a try but it causes issues with text overflow that I could not solve, for example:
![image](https://github.com/user-attachments/assets/26e6e411-29d3-4208-a3a3-d130dd09d1e7)

So I would prefer to go with the current and maybe have another look at tables later.

2025-02-13 12:20 UTC, sschuberth commented on plugins/commands/plugins/src/main/kotlin/PluginsCommand.kt
> +                    UnorderedList(
Maybe [this](https://github.com/ajalt/mordant/issues/109#issuecomment-1743429942) helps, though.

2025-02-13 12:21 UTC, sschuberth commented
So, to avoid any confusion, should this PR also remove `--list=plugins` from `ort requirements`?

2025-02-13 12:34 UTC, mnonnenmacher commented
> So, to avoid any confusion, should this PR also remove `--list=plugins` from `ort requirements`?

No, I added to the commit message that I want to remote it after package managers have been migrated.

2025-02-13 12:42 UTC, sschuberth commented on plugins/commands/plugins/src/main/kotlin/PluginsCommand.kt
> +                    UnorderedList(
Then maybe [this](https://github.com/ajalt/mordant/issues/140#issuecomment-1845816734)?

2025-02-13 12:44 UTC, sschuberth approved these changes

2025-02-13 12:44 UTC, sschuberth commented on plugins/commands/plugins/src/main/kotlin/PluginsCommand.kt
> +                                option.defaultValue?.let { append(" (Default: $it)") }
Nit: Could be `?.also {}` as the return value is unused.

2025-02-13 15:32 UTC, mnonnenmacher commented on plugins/commands/plugins/src/main/kotlin/PluginsCommand.kt
> +                    UnorderedList(
Yes, maybe that could help, would have to be tried.

2025-02-13 15:57 UTC, merged