fix(gradle-inspector): Optimize memory by caching dependency subtrees
oss-review-toolkit/ort pull request #9305
Opened 2024-10-18 13:24 UTC by wkl3nk

In large projects with many dependencies, the GradleInspector plugin often runs out of Java heap space, even when allocated 2 GB. This is due to all dependencies being stored in a large tree structure, which consumes a significant amount of memory.

This change introduces a caching mechanism for dependency subtrees of components. Instead of traversing and storing the entire dependency tree every time, the cache is checked first. If a subtree for a component already exists in the cache, a reference to this cached data is used, reducing memory consumption significantly.

Fixes #9220.

Please ensure that your pull request adheres to our [contribution guidelines](https://github.com/oss-review-toolkit/.github/blob/main/CONTRIBUTING.md). Thank you!

2024-10-20 13:26 UTC, heliocastro commented
I just checked and validated against the reproducible targets, including the demo on #9220. This patch was able to generate the output properly not showing the OutofMem behavior.
It may be a temporary solution or a definitive one; I would recommend merging it.

2024-10-20 13:28 UTC, heliocastro approved these changes
Looks good after the tests against the test repositories.

2024-10-21 05:38 UTC, oheger-bosch submitted a review, later dismissed
Great fix, thank you very much @wkl3nk

2024-10-21 09:22 UTC, sschuberth requested changes

2024-10-21 09:22 UTC, sschuberth commented on plugins/package-managers/gradle-plugin/src/main/kotlin/OrtModelBuilder.kt
> +                                    .also { globalDependencySubtrees[id.displayName] = it }
Please use `getOrPut()` instead:

    val dependencies = globalDependencySubtrees.getOrPut(id.displayName) {
        selectedComponent.dependencies.toOrtDependencies(poms, visited + id)
    }

2024-10-21 09:30 UTC, sschuberth commented
> This is due to all dependencies being stored in a large tree structure, which consumes a significant amount of memory.

BTW, this is due to *GradleInspector* using [the same `GradleModel` as the "legacy" *Gradle* analyzer](https://github.com/oss-review-toolkit/ort/blob/main/plugins/package-managers/gradle-model/src/main/kotlin/GradleModel.kt) for easier comparison. That model has several problems, one is the mentioned memory usage, the other is that dependency cycles cannot really be modeled as you run into a chick-and-egg problem with package references (you cannot refer to a dependency before it was created, but in order to create it you need to know its dependencies).

Both problems could also be solved via https://github.com/oss-review-toolkit/ort/issues/8377 which uses textual IDs instead of objects for referring to dependencies. This approach would be closer to the `DependencyGraph` model anyway... it's indeed awkward that we first use a far less efficient (temporary) memory model in `GradleModel`, just to convert it to the more efficient `DependencyGraph` later, instead of using the more efficient model to begin with.

2024-10-21 10:40 UTC, sschuberth approved these changes

2024-10-21 10:49 UTC, merged