refactor(node): Re-write Yarn to no more rely on `node_modules` file hierarchy
oss-review-toolkit/ort pull request #9427
Opened 2024-11-14 13:13 UTC by fviernau

See individual commits.

Part of: #9261.

2025-03-21 13:38 UTC, sschuberth requested changes

2025-03-21 14:16 UTC, fviernau commented on plugins/package-managers/node/src/main/kotlin/NodePackageManagerSupport.kt
> +internal fun parsePackage(packageJsonFile: File, getRemotePackageDetails: GetPackageDetailsFun): Package {
> Do you feel like addressing this, although it was wrong before?

I'll address it.

2025-03-24 07:28 UTC, fviernau commented on plugins/package-managers/node/src/main/kotlin/yarn/Yarn.kt
> +    }.mapTo(mutableListOf()) { parsePackageJson(it) }
I've made the type explicit but kept it a list, as this is more handy with debugging.

2025-03-24 08:20 UTC, fviernau commented on plugins/package-managers/node/src/main/kotlin/yarn/YarnDependencyHandler.kt
> +    override fun linkageFor(dependency: YarnListNode): PackageLinkage = PackageLinkage.DYNAMIC
I had forgotten to implement this. Now, it supports project references inbetween workspace projects.

2025-03-24 13:14 UTC, fviernau commented on plugins/package-managers/node/src/main/kotlin/yarn/YarnDependencyHandler.kt
> +    override fun linkageFor(dependency: YarnListNode): PackageLinkage = PackageLinkage.DYNAMIC
> Hmm, as I believe tests had passed for your first iteration, does that mean that this functionality was not covered by test before?

Yes, exactly.

2025-03-24 13:24 UTC, sschuberth commented on plugins/package-managers/node/src/main/kotlin/yarn/YarnDependencyHandler.kt
> +    override fun linkageFor(dependency: YarnListNode): PackageLinkage = PackageLinkage.DYNAMIC
Fair enough. Although I have to admit that this decreases confidence in the rewrite a bit, as it's now harder to judge whether it changes behavior compared to before or not.

Can I ask for your timeline to add these tests? Because *if* this refactoring broke something, then it wouldn't be so good to let it go unnoticed for too long.

2025-03-24 13:26 UTC, fviernau commented on plugins/package-managers/node/src/main/kotlin/yarn/YarnDependencyHandler.kt
> +    override fun linkageFor(dependency: YarnListNode): PackageLinkage = PackageLinkage.DYNAMIC
> Fair enough. Although I have to admit that this decreases confidence in the rewrite a bit, as it's now harder to judge whether it changes behavior compared to before or not.

Ok, then I'll make a PR prior to this one which enhance the tests.

2025-04-14 07:17 UTC, sschuberth commented on plugins/package-managers/node/src/main/kotlin/yarn/YarnDependencyHandler.kt
> +    override fun linkageFor(dependency: YarnListNode): PackageLinkage = PackageLinkage.DYNAMIC
FYI, I'm waiting for these tests before another review.

2025-04-16 10:12 UTC, fviernau commented on plugins/package-managers/node/src/main/kotlin/yarn/YarnDependencyHandler.kt
> +    override fun linkageFor(dependency: YarnListNode): PackageLinkage = PackageLinkage.DYNAMIC
It turned out that the existing implementation wasn't capable of handling it. So, I've fixed that and covered it with a test, see https://github.com/oss-review-toolkit/ort/pull/10177.

2025-04-16 12:28 UTC, fviernau commented on plugins/package-managers/node/src/main/kotlin/yarn/YarnDependencyHandler.kt
> +    override fun linkageFor(dependency: YarnListNode): PackageLinkage = PackageLinkage.DYNAMIC
ok, now it's ready again @sschuberth .

2025-04-16 13:17 UTC, sschuberth requested changes

2025-04-17 07:38 UTC, fviernau commented on plugins/package-managers/node/src/main/kotlin/yarn/Yarn.kt
> +                issues = emptyList()
`resolveDependencies()` is called for each (mapped) definition file, let's name it `D`. 
We still do get an issue for each `D`, for which the at least one project's `PackageJson` which corresponds to `D`s workspace could not be parsed. The issue creation happens here: [1]. 

[1]: https://github.com/oss-review-toolkit/ort/blob/e161da3e232c82637d79434ad5a626278b65d20c/analyzer/src/main/kotlin/PackageManager.kt#L291-L325

2025-04-17 09:11 UTC, sschuberth commented on plugins/package-managers/node/src/main/kotlin/yarn/Yarn.kt
> +                issues = emptyList()
So, you're saying that the task of catching exceptions while parsing project files is now handed over from here to upstream `PackageManager` code, correct? Or in other word, the new code assumes that if you reach this line, there were no issues with parsing the project, right?

2025-04-17 10:16 UTC, sschuberth approved these changes

2025-04-17 10:16 UTC, merged