detection of files without curation
oss-review-toolkit/ort pull request #9487
Opened 2024-11-22 12:13 UTC by kikofernandez

Based on #9435, it was stated that we could simply apply curations to files not listed in the license findings. The current PR is one such design but **breaks backwards compatibility**. I would like some feedback on how it would be preferred to deal with this. 

Below I state some of the approaches I have thought of. Any feedback is welcomed.

## PR Approach

- detects files without license and these are not added to the output of the scanner (as requested in #9435. As such, the evaluator reports errors for files without license. (**breaks backwards compatibility**)
- if we add curations, curations are applied to the unlicensed files (this is simply because of the curation mechanism)
- unlicensed files use the default value `NONE` when created as part of a `LicenseFinding`.
- **Not complete, missing tests, looking for feedback**

## Design Option

**Approach**
I have tried to look for ways to changes to the `FindingCurationMatcher.kt` (recommended by @sschuberth ). There are a bunch of methods in this file, but none of them have available the files needed from `ScanResult`s. I do not mind to "patch" all call sites that pass `findings`:
- `FindingCurationMatcher().matches(finding, curation)`
- `FindingCurationMatcher().apply(finding, curation)`
- `FindingCurationMatcher().applyAll(finding, curation)`

and add to the `findings` all files without licenses as `LicenseFinding(license="NONE"), location=...)`. In this way, a curation matcher with a glob pattern on a folder and `detected_license: NONE` can apply the curation. 

**Questions/Comments**
We apply curations to files not listed in the scanner results. 
To me, this may seem counter-intuitive, since I do not think ORT has ever dealt with files not listed in the scanner. The idea is to apply curations to unlicensed files, but I think it is more uniform if unlicensed files are listed in the scanner. Thoughts?

## Design Option 2

Add to the `.ort.yml` an option (or to the cli) to state that unlicensed files are part of the scanner and should be shown there.

**Use case**
- Opt-in to curate unlicensed files. AFAIK, unlicensed files are not considered in the `evaluator`.
From my point of view, we need to analyse [Erlang/OTP](https://github.com/erlang/otp) and would like warnings/errors for any files without license. Design option 2 makes explicit this option, and the scanner shows the truth result of scanned files.

2024-11-22 12:23 UTC, fviernau commented
I believe we should first create a proposal how this could be done, before working on an actual implementation and decide for a specific approach.

2024-11-22 13:53 UTC, kikofernandez commented
**Question1**: Should I create a proposal as a comment inside of #9435? 
**Question2**: how does one usually create a proposal? (apart from this small PR with suggestions and asking for feedback on a new approach)?

In any case, the proposals that I have thought of are written in this PR:
- Current PR proposal (breaks backwards compatibility)
- Option 1
- Option 2
- Option 3? Different approach or more guidance?

**Question3** Should I try to detail more the proposals written here? (I am new to the project and do not yet understand all possible outcomes/impact from the approaches outlined in this PR)

2024-11-22 17:40 UTC, sschuberth commented
> **Question2**: how does one usually create a proposal?

I good way would be to join our [weekly community meeting](https://github.com/oss-review-toolkit/ort/wiki/ORT-Community-Meeting) to discuss such ideas.

2024-11-22 19:41 UTC, kikofernandez commented
> > **Question2**: how does one usually create a proposal?
> 
> I good way would be to join our [weekly community meeting](https://github.com/oss-review-toolkit/ort/wiki/ORT-Community-Meeting) to discuss such ideas.

Oh, that would great! I would like to see what the community is doing, the roadmap, and learn. I will drop by for sure next Thursday!

2024-12-04 16:59 UTC, kikofernandez commented
As discussed in the weekly meeting last week: 

**Contribution**
- To make the scanner able to display all files with their license findings, where files without licenses have license `NONE`. 
- **Goal** the scanner reports license findings, including files without license
- **Implication** the curation mechanism can override files without licenses; this is important in many open-source projects, where a single license file applies to a whole folder / project (e.g., [Elixir lang](https://github.com/elixir-lang/elixir) and [Django](https://github.com/django/django/tree/main) among many others)

**Summary**
I have added a flag `includeUnlicensed` to the scanner configuration. Its default is `false`. When set to `true`, the scanner adds files without license to a `ScanResult`. These unlicensed files have their `LicenseFindings` set to `NONE`.

**Missing**
- I am struggling to test this addition and could not find other tests for the `scanner.scan`, apart from integration tests. Any guidance on testing is welcomed :)

2024-12-13 10:03 UTC, kikofernandez commented
I have addressed detected problems: fixed the implicits and the commit lint :)

2024-12-13 10:06 UTC, fviernau commented
It was a real large effort to introduce file lists (complete listing of all the files) in a non-redundant way. 
I strongly believe we should not introduce redundant data into any serialized model data structure with the implementation here, not even if it's behind a toggle. There is logic which maps the data on-the-fly, where this might fit in, but I may impact performance.

2024-12-13 10:16 UTC, kikofernandez commented
> It was a real large effort to introduce file lists (complete listing of all the files) in a non-redundant way. I strongly believe we should not introduce redundant data into any serialized model data structure with the implementation here, not even if it's behind a toggle. There is logic which maps the data on-the-fly, where this might fit in, but I may impact performance.

Could you provide some guidance for me to be able to improve this PR with a more appropriate implementation?

2025-01-02 10:54 UTC, sschuberth requested changes

2025-01-02 10:54 UTC, sschuberth commented on scanner/src/main/kotlin/Scanner.kt
> +        val filteredScanResults = filterScanResultsByVcsPaths(controller.getAllScanResults(), vcsPathsForProvenances)
Ok, a few random starting thoughts / comments:
- This code gets complex and deserves a few more code comments that explain the algorithm / intention.
- For the default case ideally no unnecessary copy should be done (like is done now in line 217). To archive that, I'd leave `val filteredScanResults` as-is in original line 195, and instead introduce a new variable like

        val scanResults = if (scannerConfig.includeUnlicensed) {
            // Do the work.
        } else {
            filteredScanResults
        }

        // ....

        return ScannerRun.EMPTY.copy(
            config = scannerConfig,
            provenances = provenances,
            scanResults = scanResults,
            files = files,
            scanners = scanners
        )

2025-01-02 10:54 UTC, sschuberth commented on scanner/src/main/kotlin/Scanner.kt
> +                    )
To reduce nesting and make the code more readable, I propose something like this (completely untested; this goes to `// Do the work.` from my comment above):

            filteredScanResults.mapTo(mutableSetOf()) { scanResult ->
                val allPaths = controller.getAllFileLists()[scanResult.provenance]?.files?.map { it.path }.orEmpty()
                val pathsWithFindings = scanResult.summary.licenseFindings.map { it.location.path }
                val pathsWithoutFindings = allPaths.filter { it !in pathsWithFindings }

                val findingsThatAreNone = pathsWithoutFindings.map {
                    LicenseFinding(SpdxConstants.NONE, TextLocation(it, UNKNOWN_LINE))
                }

                scanResult.copy(
                    summary = scanResult.summary.copy(
                        licenseFindings = scanResult.summary.licenseFindings + findingsThatAreNone
                    )
                )
            }

Due to the introduced variables, this maybe is even clear enough to not require any code comments.

2025-01-02 10:54 UTC, sschuberth commented on scanner/src/main/kotlin/Scanner.kt
> +                    )
Note that I'm using the `SpdxConstants.NONE` constant instead of `"NONE"` here, and deliberately an unknown / invalid line range. I have not checked whether this might cause any problems with some later sanity checks or so.

2025-01-21 10:08 UTC, kikofernandez commented on scanner/src/main/kotlin/Scanner.kt
> +                    )
I pushed a commit and I think it makes more sense `SpdxConstants.NOASSERTION` as files without license are unknowns. The standard also says it is preferably other alternative and only use `NONE` when there is no other viable option

2025-01-21 10:30 UTC, sschuberth commented on scanner/src/main/kotlin/Scanner.kt
> +                    )
Note that I believe we need to be able to distinguish two cases:
- First, a finding of "something" that looks like a license, but ScanCode dos not know which one, and thus there's no corresponding license text. This case currently gets mapped to `SpdxConstants.NOASSERTION`, I believe.
- Second, the case where ScanCode does not find any license in a file, which is the case of this PR. If we map this to `SpdxConstants.NOASSERTION` as well, we wouldn't be able to distinguish the two cases anymore. Therefore my thinking still is that we should use `SpdxConstants.NONE` for this case. As this goes to the *detected* license only, it should be still clear that this is a "claim from the scanner only", and you anyway need to double-check results to come up with a concluded license.

2025-01-21 10:34 UTC, kikofernandez commented on scanner/src/main/kotlin/Scanner.kt
> +                    )
Ok, now that you have mentioned this, I think you are right

2025-01-21 10:39 UTC, sschuberth commented on scanner/src/main/kotlin/Scanner.kt
> +        val scanResults = if (!scannerConfig.includeFilesWithoutFindings) {
Isn't the condition reversed here, @kikofernandez?

2025-01-21 10:53 UTC, sschuberth approved these changes

2025-01-21 12:32 UTC, sschuberth commented on scanner/src/main/kotlin/Scanner.kt
> +                val allPaths = controller.getAllFileLists()[scanResult.provenance]?.files?.map { it.path }.orEmpty()
Let's change this so to avoid warnings about `Set` conversion:

                val allPaths = controller.getAllFileLists()[scanResult.provenance]?.files?.mapTo(mutableSetOf()) {
                    it.path
                }.orEmpty()

                val pathsWithFindings = scanResult.summary.licenseFindings.mapTo(mutableSetOf()) { it.location.path }
                val pathsWithoutFindings = allPaths - pathsWithFindings

                val findingsThatAreNone = pathsWithoutFindings.mapTo(mutableSetOf()) {
                    LicenseFinding(SpdxConstants.NONE, TextLocation(it, UNKNOWN_LINE))
                }

                scanResult.copy(
                    summary = scanResult.summary.copy(
                        licenseFindings = scanResult.summary.licenseFindings + findingsThatAreNone
                    )
                )

2025-01-21 13:38 UTC, sschuberth approved these changes

2025-01-21 13:58 UTC, merged