Run unit tests on Windows
oss-review-toolkit/ort pull request #9563
Opened 2024-12-08 12:22 UTC by sschuberth

Please have a look at the individual commit messages for the details.

2024-12-08 19:16 UTC, fviernau commented on .github/workflows/build-and-test.yml
> +    strategy:
commit-msg: typo in 'tsets'

2024-12-12 17:05 UTC, mnonnenmacher requested changes

2024-12-12 17:05 UTC, mnonnenmacher commented on .github/workflows/build-and-test.yml
Commit message nit: "and least" -> "at least", and I would remove the parenthesis around "unit" because I think that's what "at least" refers to. Or just remove "at least" altogether.

2024-12-12 17:12 UTC, mnonnenmacher approved these changes

2024-12-12 17:37 UTC, merged