feat(spdx): Add file level information to SPDX projects
oss-review-toolkit/ort pull request #9646
Opened 2024-12-19 14:02 UTC by kikofernandez

In an SPDX report, the information of the project itself is converted to an SPDX package entity as it is done for external dependencies as well. However, this project entity does neither contain the attribute `licenseInfoFromFiles` nor does it contain file-level information even though the scanner found (and e.g. the web app report contains) licenses. Only detected copyright statements are included in the field `copyrightText`.

If the property `file.information.enabled` is set, file-level information for the scanned project is included.

I would like some feedback on this addition, which is linked to #8485 :) Thanks

These are the minimum set of changes required to make our use case work.

P.S. @daniel-kr I have set you as author of this PR because these are all your changes.

2025-01-02 08:53 UTC, sschuberth requested changes

2025-01-02 08:53 UTC, sschuberth commented on plugins/reporters/spdx/src/main/kotlin/Extensions.kt
> +            SpdxPackageType.PROJECT -> homepageUrl.nullOrBlankToSpdxNone()
Hmm, the homepage URL is not necessarily the download location. So I'd instead use the source artifact URL or the VCS location. As projects are usually unpublished, there usually also is no source artifact, which leaves us with the VCS location. So I'd use that and only fall back to the homepage URL, if at all. What do you think @kikofernandez?

2025-01-02 08:53 UTC, sschuberth commented on plugins/reporters/spdx/src/main/kotlin/Extensions.kt
> +            SpdxPackageType.PROJECT -> homepageUrl.nullOrBlankToSpdxNone()
A nit: In the below `when`s, you're handling the `SpdxPackageType.PROJECT` last. So for consistency I'd also handle it last here.

2025-01-02 08:53 UTC, sschuberth commented on plugins/reporters/spdx/src/main/kotlin/SpdxDocumentModelMapper.kt
> +
Nit: Please remove this superfluous empty line.

2025-01-02 08:53 UTC, sschuberth commented on plugins/reporters/spdx/src/main/kotlin/SpdxDocumentModelMapper.kt
> +                ortResult.getSpdxFiles(project.id, licenseInfoResolver, VCS, nextFileIndex)
Somewhat related to my comment above:  You're using `VCS` as the source co0de origin here, so you should use the VCS location as the download location to make that match.

2025-01-23 08:34 UTC, sschuberth commented
@kikofernandez, would you have time to proceed with this as well? I'd like to get the PR review off my plate 😉

2025-01-23 08:56 UTC, fviernau commented
> If the property `file.information.enabled` is set, file-level information for the scanned project is included.

The PR description says this. IIUC this is not present yet. Can we add such a flag?

2025-01-23 10:27 UTC, kikofernandez commented on plugins/reporters/spdx/src/main/kotlin/SpdxDocumentModelMapper.kt
> +                ortResult.getSpdxFiles(project.id, licenseInfoResolver, VCS, nextFileIndex)
I am not sure if you are implying that I need to do another change here, or that the change mentioned above makes sense due to using `VCS` here. I understand it as claiming that it makes sense based on using `VCS` information. So no change was performed.

2025-01-23 10:28 UTC, kikofernandez commented
> If the property `fileInformationEnabled` is set to true in the `SpdxDocumentReporter`, file-level information for the scanned project is included.

I meant `fileInformationEnabled` which already exists in `SpdxDocumentReporter`. Sorry for the mistake

2025-01-23 11:31 UTC, sschuberth commented
I'm not 100% sure, but I believe per Git convention footer lines should not be separated by empty lines. That is

```
Co-authored-by: Kiko Fernandez-Reyes <kiko@erlang.org>
Co-authored-by: Daniel Kreck <daniel.kreck@collaboration-factory.de>

Signed-off-by: Kiko Fernandez-Reyes <kiko@erlang.org>
```

should become

```
Co-authored-by: Kiko Fernandez-Reyes <kiko@erlang.org>
Co-authored-by: Daniel Kreck <daniel.kreck@collaboration-factory.de>
Signed-off-by: Kiko Fernandez-Reyes <kiko@erlang.org>
```

2025-01-23 11:37 UTC, sschuberth commented
There are more `SpdxDocumentReporterFunTest`s to [update](https://github.com/oss-review-toolkit/ort/actions/runs/12928164828/job/36055009701?pr=9646#step:6:2559).

2025-01-23 11:48 UTC, fviernau commented
> I meant `fileInformationEnabled` which already exists in `SpdxDocumentReporter`. Sorry for the mistake

But, I actually meant a separate toggle for file level info for projects. (My assumption is, that there are use cases where exposing a list of file of the project may be undesired, for example in some proprietary projects.)

2025-01-23 11:56 UTC, sschuberth commented
> My assumption is, that there are use cases where exposing a list of file of the project may be undesired, for example in some proprietary projects.

If this is an assumption only for now, can we leave the implementation as-is and only improve it later if the concrete need arises?

2025-01-23 12:30 UTC, sschuberth commented
> I'm not 100% sure, but I believe per Git convention footer lines should not be separated by empty lines. That is
> 
> ```
> Co-authored-by: Kiko Fernandez-Reyes <kiko@erlang.org>
> Co-authored-by: Daniel Kreck <daniel.kreck@collaboration-factory.de>
> 
> Signed-off-by: Kiko Fernandez-Reyes <kiko@erlang.org>
> ```
> 
> should become
> 
> ```
> Co-authored-by: Kiko Fernandez-Reyes <kiko@erlang.org>
> Co-authored-by: Daniel Kreck <daniel.kreck@collaboration-factory.de>
> Signed-off-by: Kiko Fernandez-Reyes <kiko@erlang.org>
> ```

I guess that broke commit-lint now, sorry for that. Please revert to having that empty line.

2025-01-23 15:12 UTC, fviernau commented
> If this is an assumption only for now, can we leave the implementation as-is and only improve it later if the concrete need arises?

My fear was that the need could be already there, so it would be blocking folks from using the latest if this is true.

2025-01-23 15:33 UTC, sschuberth commented
> My fear was that the need could be already there, so it would be blocking folks from using the latest if this is true.

I understand, but I'd that fear is unjustified unless one of those parties speaks up and participates in the community at least by filing an issue.

2025-01-23 15:38 UTC, sschuberth commented
The commit message still says  `file.information.enabled` instead of `fileInformationEnabled`.

2025-01-23 18:25 UTC, kikofernandez commented
> The commit message still says `file.information.enabled` instead of `fileInformationEnabled`.

Fixed!

2025-01-23 19:32 UTC, sschuberth commented
> ~I think there are more errors, I will look at those tomorrow~ Ok, no errors, I thought I had seen some, probably some old cache result.

But you PR now unexpectedly contains an unrelated test update. I've extracted that to https://github.com/oss-review-toolkit/ort/pull/9822. Please rebase your PR branch once that PR is merged.

2025-01-23 21:31 UTC, sschuberth approved these changes

2025-01-23 21:48 UTC, merged