Special handling for toplevel project checkouts
oss-review-toolkit/ort pull request #9657
Opened 2024-12-20 16:34 UTC by dimitris-iliou

Projects containing both .git and .repo folders in the root directory are currently not recognized as GitRepo by the analyzer. This update aims to address this issue.

2024-12-20 17:18 UTC, sschuberth requested changes

2024-12-20 17:18 UTC, sschuberth commented on scanner/src/main/kotlin/provenance/ProvenanceDownloader.kt
> +
Unfortunately, there is no commit message body to explain what the intention of this code is, what it does, and why it's needed. Specifically, why is it not enough to only swap the priority values of the VCS implementations?

2025-01-14 16:35 UTC, sschuberth commented on scanner/src/main/kotlin/provenance/ProvenanceDownloader.kt
> +
> Specifically, why is it not enough to only swap the priority values of the VCS implementations?

Do you have an answer here, @dimitris-iliou?

2025-01-15 14:45 UTC, dimitris-iliou commented on scanner/src/main/kotlin/provenance/ProvenanceDownloader.kt
> +
I will have to run and test it again with some gitrepo project because if I remember correct, there were some erros in the scanner.

2025-01-15 14:51 UTC, closed without merging